// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const FilterDisabledIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24" fill="none">
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M4 3h16v6.595l-5 2.974v7.049l-6 3v-10.05L4 9.596V3zm2 2v3.457h12V5H6z"
                fill="currentColor"
            />
        </svg>
    );
};

FilterDisabledIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default FilterDisabledIcon;
