// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { getSemanticValue } from '../../utils/cssVariables';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const MinusIcon: React.FC<Props> = ({ size = 'medium', color = getSemanticValue('foreground-primary'), ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width={sizePx} height={sizePx} viewBox="0 0 20 20">
            <path d="M15.833 10.833V9.167H4.167v1.666z" fill="currentColor" fillRule="nonzero" />
        </svg>
    );
};
export default MinusIcon;
