// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const ResendIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M18 10v12H2V10h16zM4 13.044V20h12v-6.837l-3.494 2.642a4.111 4.111 0 01-4.824.096l-.179-.131L4 13.044zM8.479.279l.316 4.67A8 8 0 1120 16.245v-2.928a6 6 0 00-9.792-6.928l4.402.453-1.892 1.892-4.847-.467-.668-.064-.244-.023-.372-6.008L8.479.28zM14.222 12H5.915l2.816 2.19c.707.55 1.677.591 2.423.12l.146-.101L14.222 12z"
                fill="currentColor"
            />
        </svg>
    );
};
export default ResendIcon;
