// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const ThumbUpFilledIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M13.937 2C15 2 15.859 3.585 15.51 4.632L14.387 8h4.173a3 3 0 01.394.026l.195.032a3 3 0 012.353 3.53l-1.2 6A3 3 0 0117.36 20H10a3 3 0 01-3-3V9.724a3 3 0 01.695-1.92l3.937-4.725C12.202 2.395 12.874 2 13.937 2zM5 9v10H3V9h2z"
                fill="currentColor"
            />
        </svg>
    );
};
export default ThumbUpFilledIcon;
