// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const ArrowDownIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24">
            <path
                d="M5 11.102l6 5.334V4h2v12.436l6-5.334v2.676L12 20l-7-6.222v-2.676z"
                fill="currentColor"
                fillRule="nonzero"
            />
        </svg>
    );
};

ArrowDownIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default ArrowDownIcon;
