// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const BackwardLastIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 12 12">
            <path
                d="M3.5 1v10H2V1h1.5zm5.441 0L10 2.071 6.118 6 10 9.929 8.941 11 4 6l1.059-1.071L8.94 1z"
                fill="currentColor"
                fillRule="nonzero"
            />
        </svg>
    );
};

BackwardLastIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default BackwardLastIcon;
