// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const ClockIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} xmlns="http://www.w3.org/2000/svg" width={sizePx} height={sizePx} fill="none">
            <path
                fill="currentColor"
                fillRule="evenodd"
                d="M17.657 17.657A8 8 0 116.343 6.342a8 8 0 0111.314 11.315zM15.827 2.76A10 10 0 002 12c0 5.5 4.47 10 10 10a10 10 0 003.827-19.239zM11 13V7h2v4.845l4.388 2.534-1 1.732L11 13z"
                clipRule="evenodd"
            />
        </svg>
    );
};
export default ClockIcon;
