// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const DirectionArrowOutlineIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24">
            <path
                d="M22 2l-9.429 22-2.095-10.476L0 11.429 22 2zm-3.808 3.807L6.706 10.73l5.47 1.094 1.093 5.469 4.923-11.486z"
                fill="currentColor"
                fillRule="nonzero"
            />
        </svg>
    );
};

DirectionArrowOutlineIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default DirectionArrowOutlineIcon;
