// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const DogIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M9.844 3a6.973 6.973 0 00-6.896 5.944L1 22h1.982l1.255-8.148c.925 1.818 3.198 2.53 5.128 1.631 1.905-.889 2.822-3.045 2.075-4.906l-.08-.185-2.108-4.519-.333-.787c.3-.056.61-.086.925-.086h1.006a4.403 4.403 0 014.196 3.055l.276.945h5.71v2.018a3 3 0 01-2.143 2.875l-4.776 1.423L13.302 20H5.323l-.317 2h9.979l.887-5.121 3.588-1.07a5 5 0 003.572-4.791V7H16.79a6.41 6.41 0 00-5.94-4H9.845zM7.07 5.846l.355.84 2.122 4.55c.407.874-.034 1.971-1.028 2.434-.944.44-2.005.13-2.458-.65l-.066-.126-1.23-2.578.16-1.077A4.968 4.968 0 017.07 5.846zM13.072 8a1 1 0 100 2 1 1 0 000-2z"
                fill="currentColor"
            />
        </svg>
    );
};
export default DogIcon;
