// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const ForwardLastIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 12 12">
            <path
                d="M8.5 11V1H10v10H8.5zm-5.441 0L2 9.929 5.882 6 2 2.071 3.059 1 8 6 6.941 7.071 3.06 11z"
                fill="currentColor"
                fillRule="nonzero"
            />
        </svg>
    );
};

ForwardLastIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default ForwardLastIcon;
