// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const PlusIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24">
            <path d="M19 13v-2h-6V5h-2v6H5v2h5.989L11 19h2v-6z" fill="currentColor" fillRule="nonzero" />
        </svg>
    );
};

PlusIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default PlusIcon;
