// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const BotIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
        >
            <path d="M16 12a2 2 0 11-4 0 2 2 0 014 0zM8 14a2 2 0 100-4 2 2 0 000 4z" fill="#1E1A1A" />
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M12 3.732a2 2 0 10-2 0V5H4a2 2 0 00-2 2v3H1a1 1 0 00-1 1v3a1 1 0 001 1h1v3a2 2 0 002 2h14a2 2 0 002-2v-3h1a1 1 0 001-1v-3a1 1 0 00-1-1h-1V7a2 2 0 00-2-2h-6V3.732zM18 18V7H4v11h14z"
                fill="#1E1A1A"
            />
        </svg>
    );
};
export default BotIcon;
