// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const CalendarAddIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M17.474 23v-3.3h-3.316v-2.2h3.316v-3.3h2.21v3.3H23v2.2h-3.316V23h-2.21zM4.21 20.8a2.133 2.133 0 01-1.562-.646A2.113 2.113 0 012 18.6V5.4c0-.605.216-1.123.65-1.554.432-.43.953-.646 1.56-.646h1.106V1h2.21v2.2h6.632V1h2.21v2.2h1.106c.608 0 1.128.215 1.56.646.434.431.65.949.65 1.554v6.71a7.475 7.475 0 00-2.21 0V9.8H4.21v8.8h7.736c0 .367.028.733.083 1.1a4.9 4.9 0 00.304 1.1H4.211zm0-13.2h13.263V5.4H4.21v2.2z"
                fill="currentColor"
            />
        </svg>
    );
};
export default CalendarAddIcon;
