// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const EditPenIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M4.895 19.105h1.35L16.453 8.897l-1.35-1.35L4.895 17.755v1.35zM3.947 21a.917.917 0 01-.675-.272.916.916 0 01-.272-.675v-2.298a1.87 1.87 0 01.545-1.326L16.453 3.545c.19-.174.398-.308.627-.403A1.87 1.87 0 0117.803 3c.252 0 .497.047.734.142.237.095.442.237.616.426l1.302 1.327c.19.173.328.379.415.616a2.05 2.05 0 010 1.432 1.775 1.775 0 01-.415.628L7.571 20.455A1.871 1.871 0 016.245 21H3.947zM15.766 8.234l-.663-.687 1.35 1.35-.687-.663z"
                fill="currentColor"
            />
        </svg>
    );
};
export default EditPenIcon;
