// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const GroupIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 32 32"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <g clipPath="url(#GroupIcon__clip0_996_29951)">
                <path
                    d="M5.333 17.333C6.8 17.333 8 16.133 8 14.667 8 13.2 6.8 12 5.333 12a2.675 2.675 0 00-2.666 2.667c0 1.466 1.2 2.666 2.666 2.666zM6.84 18.8a9.31 9.31 0 00-1.507-.133c-1.32 0-2.573.28-3.706.773A2.681 2.681 0 000 21.907V24h6v-2.147c0-1.106.307-2.146.84-3.053zm19.827-1.467c1.466 0 2.666-1.2 2.666-2.666 0-1.467-1.2-2.667-2.666-2.667A2.675 2.675 0 0024 14.667c0 1.466 1.2 2.666 2.667 2.666zM32 21.907c0-1.08-.64-2.04-1.627-2.467a9.267 9.267 0 00-3.706-.773 9.31 9.31 0 00-1.507.133c.533.907.84 1.947.84 3.053V24h6v-2.093zM21.653 18.2c-1.56-.693-3.48-1.2-5.653-1.2-2.173 0-4.093.52-5.653 1.2C8.907 18.84 8 20.28 8 21.853V24h16v-2.147c0-1.573-.907-3.013-2.347-3.653zM10.76 21.333c.12-.306.173-.52 1.213-.92A11 11 0 0116 19.667a11 11 0 014.027.746c1.026.4 1.08.614 1.213.92H10.76zM16 10.667c.733 0 1.333.6 1.333 1.333s-.6 1.333-1.333 1.333-1.333-.6-1.333-1.333.6-1.333 1.333-1.333zM16 8c-2.213 0-4 1.787-4 4s1.787 4 4 4 4-1.787 4-4-1.787-4-4-4z"
                    fill="currentColor"
                />
            </g>
            <defs>
                <clipPath id="GroupIcon__clip0_996_29951">
                    <path fill="#fff" d="M0 0h32v32H0z" />
                </clipPath>
            </defs>
        </svg>
    );
};
export default GroupIcon;
