// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const WifiOnIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = {
        ...rest,
        color
    };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M12 19.5a2.118 2.118 0 01-1.56-.64 2.134 2.134 0 01-.638-1.566c0-.617.213-1.14.638-1.566.425-.426.945-.64 1.56-.64.615 0 1.135.214 1.56.64.425.426.637.949.637 1.566 0 .618-.212 1.14-.637 1.566-.425.427-.945.64-1.56.64zm0-9.706c1.099 0 2.143.177 3.132.53a9.82 9.82 0 012.691 1.455c.293.221.444.511.451.872.007.36-.12.672-.385.937a1.29 1.29 0 01-.922.386 1.62 1.62 0 01-.99-.297 7.19 7.19 0 00-1.845-.905 6.808 6.808 0 00-2.132-.33c-.747 0-1.458.11-2.132.33-.674.22-1.289.522-1.846.905a1.565 1.565 0 01-.988.286 1.331 1.331 0 01-.923-.397 1.323 1.323 0 01-.374-.937c0-.36.146-.651.44-.872a9.595 9.595 0 012.691-1.444A9.423 9.423 0 0112 9.793zM12 4.5c1.831 0 3.556.301 5.175.904a14.367 14.367 0 014.362 2.56c.293.25.447.558.462.926.015.367-.11.684-.374.948a1.29 1.29 0 01-.923.386 1.489 1.489 0 01-.989-.342A12.065 12.065 0 0012 7.147a12.065 12.065 0 00-7.713 2.735c-.293.236-.623.35-.99.342a1.29 1.29 0 01-.922-.386A1.223 1.223 0 012 8.89a1.24 1.24 0 01.462-.927 14.367 14.367 0 014.362-2.559C8.444 4.801 10.169 4.5 12 4.5z"
                fill="currentColor"
            />
        </svg>
    );
};
export default WifiOnIcon;
