// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { getSemanticValue } from '../../utils/cssVariables';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const DuesseldorfIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M13 2v2.5h3v2h-3V8h5v2h-5v1.5h5.034l-1.753 6H13V22h-2v-4.5H7.77l-1.754-6H11V10H6V8h5V6.5H8v-2h3V2h2zm2.366 11.5H8.683l.585 2h5.513l.585-2z"
                fill="currentColor"
            />
        </svg>
    );
};
export default DuesseldorfIcon;
