// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = IconProps;
const CrosshairsOffIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M13 1h-2v2.055A9.004 9.004 0 003.055 11H1v2h2.055A9.004 9.004 0 0011 20.945V23h2v-2.055A9.004 9.004 0 0020.945 13H23v-2h-2.055A9.004 9.004 0 0013 3.055V1zm-1 18a7 7 0 100-14 7 7 0 000 14z"
                fill="currentColor"
            />
        </svg>
    );
};
export default CrosshairsOffIcon;
