import React from 'react';
import { Table, TableCell, TableHeaderCell, TableRow } from '../../../src/components/Table';

export const IconMappingsTable: React.FC = () => (
    <Table rowStyle="zebra" rowSize="small">
        <thead>
            <TableRow>
                <TableHeaderCell>Removed icons</TableHeaderCell>
                <TableHeaderCell>Alternative</TableHeaderCell>
            </TableRow>
        </thead>
        <tbody>
            <TableRow>
                <TableCell>BackwardSmallIcon</TableCell>
                <TableCell>BackwardLastIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ChevronDownSmallIcon</TableCell>
                <TableCell>ChevronDownIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ChevronLeftSmallIcon</TableCell>
                <TableCell>ChevronLeftIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ChevronRightSmallIcon</TableCell>
                <TableCell>ChevronRightIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ChevronUpSmallIcon</TableCell>
                <TableCell>ChevronUpIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>DownloadSmallIcon</TableCell>
                <TableCell>DownloadIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ForwardSmallIcon</TableCell>
                <TableCell>ForwardLastIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SearchSmallIcon</TableCell>
                <TableCell>MagnifyingGlassIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>XSmallIcon</TableCell>
                <TableCell>CloseIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>AirportIcon</TableCell>
                <TableCell>PlaneIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>EcoIcon</TableCell>
                <TableCell>LeafSolidIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>GearIcon</TableCell>
                <TableCell>CogIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>HeartIcon</TableCell>
                <TableCell>HeartSolidIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>HomeIcon</TableCell>
                <TableCell>HouseIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>InfoCircleIcon</TableCell>
                <TableCell>InfoCircleOutlineIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ListUnorderedIcon</TableCell>
                <TableCell>ListIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>PrebookingIcon</TableCell>
                <TableCell>CalendarCheckedIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SearchIcon</TableCell>
                <TableCell>MagnifyingGlassIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>XIcon</TableCell>
                <TableCell>CloseIcon</TableCell>
            </TableRow>
        </tbody>
    </Table>
);
