import React from 'react';
import { Table, TableCell, TableHeaderCell, TableRow } from '../../../src/components/Table';

export const IconMappingsTable: React.FC = () => (
    <Table rowStyle="zebra" rowSize="small">
        <thead>
            <TableRow>
                <TableHeaderCell>Removed icons</TableHeaderCell>
                <TableHeaderCell>Alternative</TableHeaderCell>
            </TableRow>
        </thead>
        <tbody>
            <TableRow>
                <TableCell>BackwardSmallIcon</TableCell>
                <TableCell>BackwardLastIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ChevronDownSmallIcon</TableCell>
                <TableCell>ChevronDownIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ChevronLeftSmallIcon</TableCell>
                <TableCell>ChevronLeftIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ChevronRightSmallIcon</TableCell>
                <TableCell>ChevronRightIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ChevronUpSmallIcon</TableCell>
                <TableCell>ChevronUpIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>DownloadSmallIcon</TableCell>
                <TableCell>DownloadIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ForwardSmallIcon</TableCell>
                <TableCell>ForwardLastIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SearchSmallIcon</TableCell>
                <TableCell>MagnifyingGlassIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>XSmallIcon</TableCell>
                <TableCell>CloseIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>AirportIcon</TableCell>
                <TableCell>PlaneIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>EcoIcon</TableCell>
                <TableCell>LeafSolidIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>GearIcon</TableCell>
                <TableCell>CogIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>HeartIcon</TableCell>
                <TableCell>HeartSolidIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>HomeIcon</TableCell>
                <TableCell>HouseIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>InfoCircleIcon</TableCell>
                <TableCell>InfoCircleOutlineIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ListUnorderedIcon</TableCell>
                <TableCell>ListIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>PrebookingIcon</TableCell>
                <TableCell>CalendarCheckedIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SearchIcon</TableCell>
                <TableCell>MagnifyingGlassIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>XIcon</TableCell>
                <TableCell>CloseIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell colSpan={2} textAlign="left" style={{ fontWeight: 'bold' }}>
                    Actions
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>AlertIcon</TableCell>
                <TableCell>WarningIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CheckCircleOutlineIcon</TableCell>
                <TableCell>CheckCircleIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CheckCircleSolidIcon</TableCell>
                <TableCell>CheckCircleFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CloseIcon</TableCell>
                <TableCell>XCrossIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CloseCircleSolidIcon</TableCell>
                <TableCell>XCrossCircleFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CloseCircleOutlineIcon</TableCell>
                <TableCell>XCrossCircleIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>EnvelopeReinviteIcon</TableCell>
                <TableCell>ResendIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>EyeOpenIcon</TableCell>
                <TableCell>EyeIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>MagnifyingGlassIcon</TableCell>
                <TableCell>MagnifierIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>MinusCircleSolidIcon</TableCell>
                <TableCell>MinusCircleFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>MinusCircleOutlineIcon</TableCell>
                <TableCell>MinusCircleIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>PlusCircleOutlineIcon</TableCell>
                <TableCell>PlusCircleIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>PlusCircleSolidIcon</TableCell>
                <TableCell>PlusCircleFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ShareIcon</TableCell>
                <TableCell>UploadIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ThumbDownSolidIcon</TableCell>
                <TableCell>ThumbDownFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ThumbDownOutlineIcon</TableCell>
                <TableCell>ThumbDownIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ThumbUpSolidIcon</TableCell>
                <TableCell>ThumbUpFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ThumbUpOutlineIcon</TableCell>
                <TableCell>ThumbUpIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>TrashBinIcon</TableCell>
                <TableCell>TrashIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>WarningSolidIcon</TableCell>
                <TableCell>WarningFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell colSpan={2} textAlign="left" style={{ fontWeight: 'bold' }}>
                    Basic
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>FlagOutlineIcon</TableCell>
                <TableCell>FlagIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>FreeNowArrowIcon</TableCell>
                <TableCell>FreenowLogoIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>MegaphoneSolidIcon</TableCell>
                <TableCell>MegaphoneFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>MegaphoneOutlineIcon</TableCell>
                <TableCell>MegaphoneIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>StarCircleSolidIcon</TableCell>
                <TableCell>StarCircleFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell colSpan={2} textAlign="left" style={{ fontWeight: 'bold' }}>
                    Battery
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>Battery100Icon</TableCell>
                <TableCell>BatteryFullIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BatteryGenericIcon</TableCell>
                <TableCell>BatteryIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>Fuel0Icon</TableCell>
                <TableCell>FuelEmptyIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>Fuel100Icon</TableCell>
                <TableCell>FuelFullIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>FuelGenericIcon</TableCell>
                <TableCell>FuelIcon</TableCell>
            </TableRow>

            <TableRow>
                <TableCell colSpan={2} textAlign="left" style={{ fontWeight: 'bold' }}>
                    Brands
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>AmericanExpressIcon</TableCell>
                <TableCell>AmexIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BrandsConcurIcon</TableCell>
                <TableCell>ConcurIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BrandsMercedesIcon</TableCell>
                <TableCell>MercedesIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BrandsMilesAndMoreIcon</TableCell>
                <TableCell>LufthansaIcon</TableCell>
            </TableRow>

            <TableRow>
                <TableCell colSpan={2} textAlign="left" style={{ fontWeight: 'bold' }}>
                    Mobility
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BikeSolidIcon</TableCell>
                <TableCell>BikeFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BikeOutlineIcon</TableCell>
                <TableCell>BikeIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BikeScooterSolidIcon</TableCell>
                <TableCell>BikeScooterFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BikeScooterOutlineIcon</TableCell>
                <TableCell>BikeScooterIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BlackCabSolidIcon</TableCell>
                <TableCell>BlackCabFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BlackCabOutlineIcon</TableCell>
                <TableCell>BlackCabIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BusSolidIcon</TableCell>
                <TableCell>BusFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BusOutlineIcon</TableCell>
                <TableCell>BusIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CarOutlineIcon</TableCell>
                <TableCell>CarIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CarSolidIcon</TableCell>
                <TableCell>CarFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>PersonHailingSolidIcon</TableCell>
                <TableCell>HailingFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>PersonHailingOutlineIcon</TableCell>
                <TableCell>HailingIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>KeySolidIcon</TableCell>
                <TableCell>KeyFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>KeyOutlineIcon</TableCell>
                <TableCell>KeyIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>MopedSolidIcon</TableCell>
                <TableCell>MopedFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>MopedOutlineIcon</TableCell>
                <TableCell>MopedIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ScooterOutlineIcon</TableCell>
                <TableCell>ScooterIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ScooterSolidIcon</TableCell>
                <TableCell>ScooterFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>TrainSolidIcon</TableCell>
                <TableCell>TrainFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>TrainOutlineIcon</TableCell>
                <TableCell>TrainIcon</TableCell>
            </TableRow>

            <TableRow>
                <TableCell colSpan={2} textAlign="left" style={{ fontWeight: 'bold' }}>
                    Navigation
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CrosshairsIcon</TableCell>
                <TableCell>CrosshairOnIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>DirectionArrowCircleOutlineIcon</TableCell>
                <TableCell>NorthArrowCircleIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>DirectionArrowOutlineIcon</TableCell>
                <TableCell>NorthArrowIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>DirectionArrowSolidIcon</TableCell>
                <TableCell>NorthArrowFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>MortarboardIcon</TableCell>
                <TableCell>EducationIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>PlaneIcon</TableCell>
                <TableCell>PlaneDepartureIcon</TableCell>
            </TableRow>

            <TableRow>
                <TableCell colSpan={2} textAlign="left" style={{ fontWeight: 'bold' }}>
                    Options
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CalendarCheckedIcon</TableCell>
                <TableCell>CalendarCheckIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CheckShieldIcon</TableCell>
                <TableCell>ShieldIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SpeechbubblesCommentIcon</TableCell>
                <TableCell>ThreeDotsBubbleIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SpeechbubblesPairIcon</TableCell>
                <TableCell>ChatIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SpeechbubblesSingleIcon</TableCell>
                <TableCell>TwoLinesBubbleIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>CogIcon</TableCell>
                <TableCell>ScrewNutIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SheetSolidIcon</TableCell>
                <TableCell>DocumentFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SheetOutlineIcon</TableCell>
                <TableCell>DocumentIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>FavoriteBannerOutlineIcon</TableCell>
                <TableCell>StarBannerIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>FavoriteBannerSolidIcon</TableCell>
                <TableCell>StarBannerFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SpeedometerIcon</TableCell>
                <TableCell>GaugeIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>HeartSolidIcon</TableCell>
                <TableCell>HeartFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>HeartOutlineIcon</TableCell>
                <TableCell>HeartIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>InfoCircleSolidIcon</TableCell>
                <TableCell>InfoCircleFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>InfoCircleOutlineIcon</TableCell>
                <TableCell>InfoCircleIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LockClosedIcon</TableCell>
                <TableCell>LockIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LegalBannerSolidIcon</TableCell>
                <TableCell>ParagraphBannerFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LegalBannerOutlineIcon</TableCell>
                <TableCell>ParagraphBannerIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ProfileSolidIcon</TableCell>
                <TableCell>ProfileFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ProfileOutlineIcon</TableCell>
                <TableCell>ProfileIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>StarOutlineIcon</TableCell>
                <TableCell>StarIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>StarSolidIcon</TableCell>
                <TableCell>StarFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>StopWatchIcon</TableCell>
                <TableCell>StopwatchIcon</TableCell>
            </TableRow>

            <TableRow>
                <TableCell colSpan={2} textAlign="left" style={{ fontWeight: 'bold' }}>
                    Payment
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BankNoteIcon</TableCell>
                <TableCell>CashBillIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>TravelExpensesIcon</TableCell>
                <TableCell>BusinessDocsIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>TippingIcon</TableCell>
                <TableCell>CashCoinsIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>DigitalPaymentIcon</TableCell>
                <TableCell>PayByAppIcon</TableCell>
            </TableRow>

            <TableRow>
                <TableCell colSpan={2} textAlign="left" style={{ fontWeight: 'bold' }}>
                    Service Type
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BoltCircleIcon</TableCell>
                <TableCell>LightningIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BoltOutlineIcon</TableCell>
                <TableCell>LightningIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>BoltSolidIcon</TableCell>
                <TableCell>LightningFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>WheelchairOutlineIcon</TableCell>
                <TableCell>AccessibilityIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>WheelchairSolidIcon</TableCell>
                <TableCell>AccessibilityFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>TwoPeopleSolidIcon</TableCell>
                <TableCell>GroupFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>TwoPeopleCircleIcon</TableCell>
                <TableCell>GroupIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>TwoPeopleOutlineIcon</TableCell>
                <TableCell>GroupIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LeafSolidIcon</TableCell>
                <TableCell>LeafFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LeafOutlineIcon</TableCell>
                <TableCell>LeafIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LiteCircleIcon</TableCell>
                <TableCell>LeafIcon</TableCell>
            </TableRow>

            <TableRow>
                <TableCell colSpan={2} textAlign="left" style={{ fontWeight: 'bold' }}>
                    Trip
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SurgeCircleSolidIcon</TableCell>
                <TableCell>BarChartCircleFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>SurgeCircleOutlineIcon</TableCell>
                <TableCell>BarChartCircleIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>ChangeDestinationIcon</TableCell>
                <TableCell>TurnRightIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>DestinationIcon</TableCell>
                <TableCell>DotIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>PickUpIcon</TableCell>
                <TableCell>DotIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LabelCheckedIcon</TableCell>
                <TableCell>TagIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LabelIcon</TableCell>
                <TableCell>TagIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LabelOutlineIcon</TableCell>
                <TableCell>TagIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LabelPlusIcon</TableCell>
                <TableCell>TagIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>LabelSolidIcon</TableCell>
                <TableCell>TagFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>PersonSolidIcon</TableCell>
                <TableCell>PersonFilledIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>PersonOutlineIcon</TableCell>
                <TableCell>PersonIcon</TableCell>
            </TableRow>
            <TableRow>
                <TableCell>DriverpHeartIcon</TableCell>
                <TableCell>PersonHeartIcon</TableCell>
            </TableRow>
        </tbody>
    </Table>
);
