// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = IconProps;
const AccessibilityFilledIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M16 17a6 6 0 11-4.51-5.814l.82-1.847A8 8 0 0010 9a7.965 7.965 0 00-4.8 1.6L3.867 9.1A9.957 9.957 0 0110 7c1.79 0 3.47.47 4.925 1.295l-1.612 3.702A6.018 6.018 0 0115.66 15h2.96l2.276 4.553-1.79.894L17.383 17H16zm.5-9a3.5 3.5 0 110-7 3.5 3.5 0 010 7z"
                fill="currentColor"
            />
        </svg>
    );
};
export default AccessibilityFilledIcon;
