// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { getSemanticValue } from '../../utils/cssVariables';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const LightningIcon: React.FC<Props> = ({
    size = 'medium',
    color = getSemanticValue('foreground-primary'),
    ...rest
}) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 17 22" xmlns="http://www.w3.org/2000/svg">
            <path
                d="M12 0l-1 8h6L5 22l.448-3.586 2.363-2.781-.002.016L12.652 10H8.734l.457-3.65L4.348 12h3.918l-.376 3H5.875L6 14H0L12 0z"
                fillRule="nonzero"
                fill="currentColor"
            />
        </svg>
    );
};
export default LightningIcon;
