// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const WheelchairCircleIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 28">
            <path
                d="M14 2c6.627 0 12 5.373 12 12s-5.373 12-12 12S2 20.627 2 14 7.373 2 14 2zm0 2C8.477 4 4 8.477 4 14s4.477 10 10 10 10-4.477 10-10S19.523 4 14 4zm-2.472 6.364c1.322 0 2.563.342 3.636.941l-1.19 2.693a4.387 4.387 0 011.732 2.184h2.185l1.68 3.31-1.32.651-1.273-2.507h-1.02c0 2.41-1.984 4.364-4.43 4.364-2.447 0-4.43-1.954-4.43-4.364s1.983-4.363 4.43-4.363c.38 0 .748.047 1.1.135l.606-1.343a5.99 5.99 0 00-1.706-.247 5.94 5.94 0 00-3.544 1.164L7 11.892a7.423 7.423 0 014.528-1.528zM16.327 6c1.427 0 2.584 1.14 2.584 2.545 0 1.406-1.157 2.546-2.584 2.546s-2.584-1.14-2.584-2.546C13.743 7.14 14.9 6 16.327 6z"
                fill="#000F1F"
                fillRule="evenodd"
            />
        </svg>
    );
};

WheelchairCircleIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default WheelchairCircleIcon;
