// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const ForwardLastIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24" fill="none">
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M16 5h2v14h-2V5zM5 5l6.175 7L5 19h2.676l6.222-7-6.222-7H5z"
                fill="currentColor"
            />
        </svg>
    );
};

ForwardLastIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default ForwardLastIcon;
