// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const ForwardIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24">
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M4 5l6.175 7L4 19h2.676l6.222-7-6.222-7H4zm7.5 0l6.175 7-6.175 7h2.676l6.222-7-6.222-7H11.5z"
                fill="currentColor"
            />
        </svg>
    );
};

ForwardIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default ForwardIcon;
