// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const PayByAppIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M14 2a3 3 0 013 3v4h-2V5a1 1 0 00-1-1H8a1 1 0 00-1 1v14a1 1 0 001 1h6a1 1 0 001-1v-6h-3.5v-2h9L18 8h2.5l3.5 4-3.5 4H18l2.5-3H17v6a3 3 0 01-3 3H8a3 3 0 01-3-3V5a3 3 0 013-3h6zm-3 15a1 1 0 110 2 1 1 0 010-2z"
                fill="currentColor"
            />
        </svg>
    );
};
export default PayByAppIcon;
