// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const AO: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <filter x="-5.4%" y="-16.1%" width="110.7%" height="132.1%" filterUnits="objectBoundingBox" id="AO__d">
                    <feMorphology radius={0.5} operator="dilate" in="SourceAlpha" result="shadowSpreadOuter1" />
                    <feOffset in="shadowSpreadOuter1" result="shadowOffsetOuter1" />
                    <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0" in="shadowOffsetOuter1" />
                </filter>
                <filter x="-5.4%" y="-14.1%" width="110.7%" height="128.1%" filterUnits="objectBoundingBox" id="AO__f">
                    <feMorphology radius={0.5} operator="dilate" in="SourceAlpha" result="shadowSpreadOuter1" />
                    <feOffset in="shadowSpreadOuter1" result="shadowOffsetOuter1" />
                    <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0" in="shadowOffsetOuter1" />
                </filter>
                <filter x="-8.1%" y="-6.3%" width="116.3%" height="125.4%" filterUnits="objectBoundingBox" id="AO__h">
                    <feOffset dy={1} in="SourceAlpha" result="shadowOffsetOuter1" />
                    <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0" in="shadowOffsetOuter1" />
                </filter>
                <path id="AO__e" d="M0 10.667h28V20H0z" />
                <path id="AO__g" d="M0 0h28v10.667H0z" />
                <path
                    d="M14.174 11.806l-1.877-1.251a.667.667 0 01.74-1.11l2.047 1.365a2.667 2.667 0 00-1.67-3.818.667.667 0 11.345-1.287 4 4 0 012.439 5.848l.838.559a.667.667 0 11-.74 1.11l-.949-.634a3.996 3.996 0 01-3.659.844.667.667 0 11.345-1.288 2.66 2.66 0 002.141-.338zm-1.507-3.14a.667.667 0 110-1.333.667.667 0 010 1.334z"
                    id="AO__i"
                />
                <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="AO__b">
                    <stop stopColor="#FF323E" offset="0%" />
                    <stop stopColor="#FD0D1B" offset="100%" />
                </linearGradient>
                <rect id="AO__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="AO__c" fill="#fff">
                    <use xlinkHref="#AO__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#AO__a" />
                <path fill="url(#AO__b)" mask="url(#AO__c)" d="M0 0h28v20H0z" />
                <g mask="url(#AO__c)">
                    <use fill="#000" filter="url(#AO__d)" xlinkHref="#AO__e" />
                    <use fill="#262626" xlinkHref="#AO__e" />
                </g>
                <g mask="url(#AO__c)">
                    <use fill="#000" filter="url(#AO__f)" xlinkHref="#AO__g" />
                    <use fill="#DD2137" xlinkHref="#AO__g" />
                </g>
                <g fillRule="nonzero" mask="url(#AO__c)">
                    <use fill="#000" filter="url(#AO__h)" xlinkHref="#AO__i" />
                    <use fill="#F8D84B" xlinkHref="#AO__i" />
                </g>
            </g>
        </svg>
    );
};
export default AO;
