// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const AW: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <filter x="-7.1%" y="-5%" width="114.3%" height="120%" filterUnits="objectBoundingBox" id="AW__c">
                    <feOffset dy={1} in="SourceAlpha" result="shadowOffsetOuter1" />
                    <feGaussianBlur stdDeviation={0.5} in="shadowOffsetOuter1" result="shadowBlurOuter1" />
                    <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.16 0" in="shadowBlurOuter1" />
                </filter>
                <rect id="AW__a" x={0} y={0} width={28} height={20} rx={2} />
                <path id="AW__d" d="M0 0h28v20H0z" />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="AW__b" fill="#fff">
                    <use xlinkHref="#AW__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#AW__a" />
                <g mask="url(#AW__b)">
                    <use fill="#000" filter="url(#AW__c)" xlinkHref="#AW__d" />
                    <use fill="#4189DD" xlinkHref="#AW__d" />
                </g>
                <path
                    d="M5.335 5.986l-1.924.604.605-1.923-.605-1.924 1.924.604 1.924-.604-.605 1.924.605 1.923-1.924-.604z"
                    stroke="#FFF"
                    strokeWidth={0.667}
                    fill="#D21034"
                    mask="url(#AW__b)"
                    transform="rotate(135 5.335 4.667)"
                />
                <path fill="#F9D616" mask="url(#AW__b)" d="M0 14.667h28V16H0zM0 12h28v1.333H0z" />
            </g>
        </svg>
    );
};
export default AW;
