// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const AZ: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <defs>
                <filter x="-12.5%" y="-12.5%" width="125%" height="150%" filterUnits="objectBoundingBox" id="AZ__c">
                    <feOffset dy={1} in="SourceAlpha" result="shadowOffsetOuter1" />
                    <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0" in="shadowOffsetOuter1" />
                </filter>
                <rect id="AZ__a" x={0} y={0} width={28} height={20} rx={2} />
                <path
                    d="M15.111 8.337a1.667 1.667 0 100 3.326 2 2 0 110-3.326zm.222 2.33a.667.667 0 110-1.334.667.667 0 010 1.334z"
                    id="AZ__d"
                />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="AZ__b" fill="#fff">
                    <use xlinkHref="#AZ__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#AZ__a" />
                <path fill="#24AAD5" mask="url(#AZ__b)" d="M0 0h28v6.667H0z" />
                <path fill="#21BF75" mask="url(#AZ__b)" d="M0 13.333h28V20H0z" />
                <path fill="#ED1845" mask="url(#AZ__b)" d="M0 6.667h28v6.667H0z" />
                <g mask="url(#AZ__b)">
                    <use fill="#000" filter="url(#AZ__c)" xlinkHref="#AZ__d" />
                    <use fill="#FFF" xlinkHref="#AZ__d" />
                </g>
            </g>
        </svg>
    );
};

AZ.defaultProps = {};
export default AZ;
