// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const BD: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="BD__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="BD__b" fill="#fff">
                    <use xlinkHref="#BD__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#BD__a" />
                <path fill="#128363" mask="url(#BD__b)" d="M0 0h28v20H0z" />
                <circle fill="#F23C53" mask="url(#BD__b)" cx={12.667} cy={10} r={6} />
            </g>
        </svg>
    );
};
export default BD;
