// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const BT: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="BT__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="BT__b" fill="#fff">
                    <use xlinkHref="#BT__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#BT__a" />
                <path fill="#FF5F38" mask="url(#BT__b)" d="M0 0h28v20H0z" />
                <path fill="#FFD951" mask="url(#BT__b)" d="M0 20L28 0H0z" />
            </g>
        </svg>
    );
};
export default BT;
