// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const BW: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="BW__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="BW__b" fill="#fff">
                    <use xlinkHref="#BW__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#BW__a" />
                <path fill="#8BBDEA" mask="url(#BW__b)" d="M0 0h28v6.667H0zM0 13.333h28V20H0z" />
                <path fill="#FFF" mask="url(#BW__b)" d="M0 6.667h28v6.667H0z" />
                <path fill="#262626" mask="url(#BW__b)" d="M0 8h28v4H0z" />
            </g>
        </svg>
    );
};
export default BW;
