// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const CA: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="CA__Ebene_1"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.CA__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path
                d="M2 0h24c1.1 0 2 .9 2 2.1V18c0 1.1-.9 2.1-2 2.1H2c-1.1 0-2-.9-2-2.1V2.1C0 .9.9 0 2 0z"
                fill="#fff"
            />
            <defs>
                <filter
                    id="CA__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={20}
                    y={0}
                    width={8}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={20} y={0} width={8} height={20} id="CA__mask-2_1_">
                <g filter="url(#CA__Adobe_OpacityMaskFilter)">
                    <path
                        id="CA__path-1_1_"
                        className="CA__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="CA__Mask"
                mask="url(#CA__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ff3131"
                d="M20 0h8v20h-8z"
            />
            <defs>
                <filter
                    id="CA__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={8}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={8} height={20} id="CA__mask-2_2_">
                <g filter="url(#CA__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="CA__path-1_2_"
                        className="CA__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="CA__Rectangle-2"
                mask="url(#CA__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ff3131"
                d="M0 0h8v20H0z"
            />
            <defs>
                <filter
                    id="CA__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={9.3}
                    y={5.3}
                    width={9.3}
                    height={9.3}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={9.3} y={5.3} width={9.3} height={9.3} id="CA__mask-2_3_">
                <g filter="url(#CA__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="CA__path-1_3_"
                        className="CA__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="CA__Rectangle-66"
                d="M15.6 9.8c-.1.1-.2.1-.2-.1l.6-3-1.3.7-.7-2-.7 2-1.3-.7.6 3c0 .2 0 .2-.2.1l-.9-.9c-.1-.1-.3-.1-.5 0l-.4.4-1.3-.6.7 1.3-.4.4c-.1.1-.1.3 0 .5l1.8 1.8h2l.3 2h.7l.3-2h2l1.8-1.8c.1-.1.1-.3 0-.5L18 10l.7-1.3-1.3.7L17 9c-.1-.1-.3-.1-.5 0l-.9.8z"
                mask="url(#CA__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ff3131"
            />
        </svg>
    );
};

CA.defaultProps = {};
export default CA;
