// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const CF: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="CF__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.CF__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path
                d="M2 0h24c1.1 0 2 .9 2 2.1V18c0 1.1-.9 2.1-2 2.1H2c-1.1 0-2-.9-2-2.1V2.1C0 .9.9 0 2 0z"
                fill="#fff"
            />
            <defs>
                <filter
                    id="CF__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={5.3}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={5.3} id="CF__mask-2_1_">
                <g filter="url(#CF__Adobe_OpacityMaskFilter)">
                    <path
                        id="CF__path-1_1_"
                        className="CF__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="CF__Rectangle-2"
                mask="url(#CF__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#083d96"
                d="M0 0h28v5.3H0z"
            />
            <defs>
                <filter
                    id="CF__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={9.3}
                    width={28}
                    height={5.3}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={9.3} width={28} height={5.3} id="CF__mask-2_2_">
                <g filter="url(#CF__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="CF__path-1_2_"
                        className="CF__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#CF__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#37ae39"
                d="M0 9.3h28v5.3H0z"
            />
            <defs>
                <filter
                    id="CF__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={14.7}
                    width={28}
                    height={5.3}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={14.7} width={28} height={5.3} id="CF__mask-2_3_">
                <g filter="url(#CF__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="CF__path-1_3_"
                        className="CF__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#CF__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ffd13f"
                d="M0 14.7h28V20H0z"
            />
            <defs>
                <filter
                    id="CF__Adobe_OpacityMaskFilter_3_"
                    filterUnits="userSpaceOnUse"
                    x={10.7}
                    y={0}
                    width={6.7}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={10.7} y={0} width={6.7} height={20} id="CF__mask-2_4_">
                <g filter="url(#CF__Adobe_OpacityMaskFilter_3_)">
                    <path
                        id="CF__path-1_4_"
                        className="CF__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#CF__mask-2_4_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#e42346"
                d="M10.7 0h6.7v20h-6.7z"
            />
            <defs>
                <filter
                    id="CF__Adobe_OpacityMaskFilter_4_"
                    filterUnits="userSpaceOnUse"
                    x={2.8}
                    y={0.7}
                    width={3.8}
                    height={3.6}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={2.8} y={0.7} width={3.8} height={3.6} id="CF__mask-2_5_">
                <g filter="url(#CF__Adobe_OpacityMaskFilter_4_)">
                    <path
                        id="CF__path-1_5_"
                        className="CF__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="CF__Star-8"
                mask="url(#CF__mask-2_5_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ffd03b"
                d="M4.7 3.4l-1.2.9.4-1.4L2.8 2h1.4L4.7.7 5.1 2h1.5l-1.2.9.4 1.4z"
            />
        </svg>
    );
};
export default CF;
