// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const CG: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <defs>
                <rect id="CG__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="CG__b" fill="#fff">
                    <use xlinkHref="#CG__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#CG__a" />
                <path fill="#F33630" mask="url(#CG__b)" d="M6.667 18.667L26.667 0H28v20H6.667z" />
                <path
                    fill="#009643"
                    mask="url(#CG__b)"
                    transform="rotate(180 10.667 10)"
                    d="M0 18.667L20 0h1.333v20H0z"
                />
                <path
                    fill="#FCDF4A"
                    mask="url(#CG__b)"
                    transform="rotate(134 14.412 9.533)"
                    d="M-4.92 6.2h38.666v6.666H-4.921z"
                />
            </g>
        </svg>
    );
};

CG.defaultProps = {};
export default CG;
