// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const CH: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <defs>
                <rect id="CH__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="CH__b" fill="#fff">
                    <use xlinkHref="#CH__a" />
                </mask>
                <rect fill="red" mask="url(#CH__b)" x={4} width={20} height={20} rx={2} />
                <path
                    d="M12 12H8.341A.34.34 0 018 11.659V8.341A.34.34 0 018.341 8H12V4.341A.34.34 0 0112.341 4h3.318a.34.34 0 01.341.341V8h3.659a.34.34 0 01.341.341v3.318a.34.34 0 01-.341.341H16v3.659a.34.34 0 01-.341.341h-3.318a.34.34 0 01-.341-.341V12z"
                    fill="#FFF"
                    mask="url(#CH__b)"
                />
            </g>
        </svg>
    );
};

CH.defaultProps = {};
export default CH;
