// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const CI: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="CI__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.CI__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path
                d="M2 0h24c1.1 0 2 .9 2 2.1V18c0 1.1-.9 2.1-2 2.1H2c-1.1 0-2-.9-2-2.1V2.1C0 .9.9 0 2 0z"
                fill="#f5f5f5"
            />
            <defs>
                <filter
                    id="CI__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={18.7}
                    y={0}
                    width={9.3}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={18.7} y={0} width={9.3} height={20} id="CI__mask-2_1_">
                <g filter="url(#CI__Adobe_OpacityMaskFilter)">
                    <path
                        id="CI__path-1_1_"
                        className="CI__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="CI__Mask"
                mask="url(#CI__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#1dc87d"
                d="M18.7 0H28v20h-9.3z"
            />
            <defs>
                <filter
                    id="CI__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={9.3}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={9.3} height={20} id="CI__mask-2_2_">
                <g filter="url(#CI__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="CI__path-1_2_"
                        className="CI__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="CI__Rectangle-2"
                mask="url(#CI__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#f89242"
                d="M0 0h9.3v20H0z"
            />
        </svg>
    );
};
export default CI;
