// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const CO: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <defs>
                <filter x="-5.4%" y="-28.1%" width="110.7%" height="156.2%" filterUnits="objectBoundingBox" id="CO__c">
                    <feMorphology radius={0.5} operator="dilate" in="SourceAlpha" result="shadowSpreadOuter1" />
                    <feOffset in="shadowSpreadOuter1" result="shadowOffsetOuter1" />
                    <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0" in="shadowOffsetOuter1" />
                </filter>
                <filter x="-5.4%" y="-28.1%" width="110.7%" height="156.2%" filterUnits="objectBoundingBox" id="CO__e">
                    <feMorphology radius={0.5} operator="dilate" in="SourceAlpha" result="shadowSpreadOuter1" />
                    <feOffset in="shadowSpreadOuter1" result="shadowOffsetOuter1" />
                    <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0" in="shadowOffsetOuter1" />
                </filter>
                <path id="CO__d" d="M0 9.333h28v5.333H0z" />
                <path id="CO__f" d="M0 14.667h28V20H0z" />
                <rect id="CO__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="CO__b" fill="#fff">
                    <use xlinkHref="#CO__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#CO__a" />
                <g mask="url(#CO__b)">
                    <use fill="#000" filter="url(#CO__c)" xlinkHref="#CO__d" />
                    <use fill="#0748AE" xlinkHref="#CO__d" />
                </g>
                <g mask="url(#CO__b)">
                    <use fill="#000" filter="url(#CO__e)" xlinkHref="#CO__f" />
                    <use fill="#DE2035" xlinkHref="#CO__f" />
                </g>
                <path fill="#FFD935" mask="url(#CO__b)" d="M0 0h28v9.333H0z" />
            </g>
        </svg>
    );
};

CO.defaultProps = {};
export default CO;
