// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const COC: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="COC__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="COC__b" fill="#fff">
                    <use xlinkHref="#COC__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#COC__a" />
                <path fill="#4499FC" mask="url(#COC__b)" d="M0 0h28v20H0z" />
                <path
                    d="M13.068 3.532c.146-.11.42-.199.599-.199.184 0 .4.133.481.296l.37.742a.598.598 0 00.479.296h1.34a.586.586 0 00.478-.296l.37-.742a.491.491 0 00-.092-.536l-.186-.186c-.133-.133-.098-.24.096-.24h.66c.186 0 .413.126.508.284l1.658 2.765c.095.157.254.408.354.559l2.3 3.45c.102.152.184.418.184.602v2.013c0 .18-.083.45-.184.602l-2.3 3.45a.68.68 0 01-.51.275H17.66c-.18 0-.442-.096-.59-.219l-3.474-2.896a1.064 1.064 0 00-.59-.219h-2.012c-.18 0-.46.067-.628.15l-3.399 1.7a.493.493 0 01-.533-.082l-.868-.869a.935.935 0 01-.233-.562v-1.34c0-.182-.087-.461-.185-.608l-.963-1.444a.63.63 0 01-.032-.584L5.18 7.64a1.17 1.17 0 01.46-.459l2.054-1.027c.169-.085.45-.189.633-.235l2.013-.503c.18-.045.441-.168.592-.28l2.136-1.603zM18 17.333h1.333l-.426.426a.337.337 0 01-.481 0L18 17.333z"
                    fill="#FFF"
                    mask="url(#COC__b)"
                />
            </g>
        </svg>
    );
};
export default COC;
