// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const DK: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <path
                d="M2 0h24c1.1 0 2 .9 2 2.1V18c0 1.1-.9 2.1-2 2.1H2c-1.1 0-2-.9-2-2.1V2.1C0 .9.9 0 2 0z"
                fill="#fff"
            />
            <defs>
                <filter id="DK__a" filterUnits="userSpaceOnUse" x={0} y={0} width={28} height={20}>
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={20} id="DK__b">
                <g filter="url(#DK__a)">
                    <path
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                        fillRule="evenodd"
                        clipRule="evenodd"
                        fill="#fff"
                    />
                </g>
            </mask>
            <path
                d="M8 0v8H0V2C0 .9.9 0 2 0h6zm4 0h14c1.1 0 2 .9 2 2v6H12V0zm16 12v6c0 1.1-.9 2-2 2H12v-8h16zM8 20H2c-1.1 0-2-.9-2-2v-6h8v8z"
                mask="url(#DK__b)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ef264d"
            />
        </svg>
    );
};

DK.defaultProps = {};
export default DK;
