// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const ER: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="ER__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="ER__b" fill="#fff">
                    <use xlinkHref="#ER__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#ER__a" />
                <path fill="#29C53F" mask="url(#ER__b)" d="M0 0h28v10H0z" />
                <path fill="#579DED" mask="url(#ER__b)" d="M0 10h28v10.667H0z" />
                <path fill="#F42D56" mask="url(#ER__b)" d="M0 20l28-10L0 0z" />
                <circle stroke="#FFC63C" strokeWidth={1.333} mask="url(#ER__b)" cx={8.667} cy={10} r={4} />
                <circle fill="#FFC63C" mask="url(#ER__b)" cx={8} cy={8.667} r={1} />
                <circle fill="#FFC63C" mask="url(#ER__b)" cx={9.333} cy={9.333} r={1} />
                <circle fill="#FFC63C" mask="url(#ER__b)" cx={8.667} cy={8} r={1} />
                <circle fill="#FFC63C" mask="url(#ER__b)" cx={8} cy={10} r={1} />
                <circle fill="#FFC63C" mask="url(#ER__b)" cx={9.333} cy={10.667} r={1} />
                <circle fill="#FFC63C" mask="url(#ER__b)" cx={8} cy={11.333} r={1} />
                <circle fill="#FFC63C" mask="url(#ER__b)" cx={9.333} cy={12} r={1} />
            </g>
        </svg>
    );
};
export default ER;
