// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const ET: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="ET__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="ET__b" fill="#fff">
                    <use xlinkHref="#ET__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#ET__a" />
                <path fill="#20AA46" mask="url(#ET__b)" d="M0 0h28v6.667H0z" />
                <path fill="#E92F3B" mask="url(#ET__b)" d="M0 13.333h28V20H0z" />
                <path fill="#FADF50" mask="url(#ET__b)" d="M0 6.667h28v6.667H0z" />
                <circle fill="#205CCA" mask="url(#ET__b)" cx={14} cy={10} r={4.667} />
                <path
                    d="M15.342 11.848l-.495-1.573 1.325-.98-1.648-.016L14 7.716l-.524 1.563-1.648.015 1.325.981-.495 1.573L14 10.89l1.342.957z"
                    stroke="#FFDB3D"
                    strokeWidth={0.667}
                    mask="url(#ET__b)"
                />
            </g>
        </svg>
    );
};
export default ET;
