// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const FI: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 20">
            <path
                d="M2 0h24c1.1 0 2 .9 2 2.1V18c0 1.1-.9 2.1-2 2.1H2c-1.1 0-2-.9-2-2.1V2.1C0 .9.9 0 2 0z"
                fill="#fff"
            />
            <defs>
                <filter id="FI__a" filterUnits="userSpaceOnUse" x={-1.3} y={-1.3} width={30.7} height={22.7}>
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={-1.3} y={-1.3} width={30.7} height={22.7} id="FI__b">
                <g filter="url(#FI__a)">
                    <path
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                        fillRule="evenodd"
                        clipRule="evenodd"
                        fill="#fff"
                    />
                </g>
            </mask>
            <path
                mask="url(#FI__b)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#0848a6"
                d="M-1.3 12H8v9.3h4V12h17.3V8H12v-9.3H8V8h-9.3z"
            />
        </svg>
    );
};
export default FI;
