// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const GE: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="GE__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.GE__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path
                d="M2 0h24c1.1 0 2 .9 2 2.1V18c0 1.1-.9 2.1-2 2.1H2c-1.1 0-2-.9-2-2.1V2.1C0 .9.9 0 2 0z"
                fill="#fff"
            />
            <defs>
                <filter
                    id="GE__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={-1.3}
                    y={-1.3}
                    width={30.7}
                    height={22.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={-1.3} y={-1.3} width={30.7} height={22.7} id="GE__mask-2_1_">
                <g filter="url(#GE__Adobe_OpacityMaskFilter)">
                    <path
                        id="GE__path-1_1_"
                        className="GE__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="GE__Rectangle-2"
                d="M12 8v-9.3h4V8h13.3v4H16v9.3h-4V12H-1.3V8H12z"
                mask="url(#GE__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ff2b37"
            />
            <defs>
                <filter
                    id="GE__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={20}
                    y={2}
                    width={4}
                    height={4}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={20} y={2} width={4} height={4} id="GE__mask-2_2_">
                <g filter="url(#GE__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="GE__path-1_2_"
                        className="GE__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="GE__Rectangle-742"
                d="M21.6 3.6L21.3 2h1.3l-.3 1.6 1.7-.3v1.3l-1.6-.3.3 1.7h-1.3l.3-1.6-1.7.3V3.3l1.6.3z"
                mask="url(#GE__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#fd0d1b"
            />
            <defs>
                <filter
                    id="GE__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={4}
                    y={2}
                    width={4}
                    height={4}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={4} y={2} width={4} height={4} id="GE__mask-2_3_">
                <g filter="url(#GE__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="GE__path-1_3_"
                        className="GE__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                d="M5.6 3.6L5.3 2h1.3l-.2 1.6L8 3.3v1.3l-1.6-.2.3 1.6H5.3l.3-1.6-1.6.3V3.3l1.6.3z"
                mask="url(#GE__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#fd0d1b"
            />
            <defs>
                <filter
                    id="GE__Adobe_OpacityMaskFilter_3_"
                    filterUnits="userSpaceOnUse"
                    x={4}
                    y={14}
                    width={4}
                    height={4}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={4} y={14} width={4} height={4} id="GE__mask-2_4_">
                <g filter="url(#GE__Adobe_OpacityMaskFilter_3_)">
                    <path
                        id="GE__path-1_4_"
                        className="GE__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                d="M5.6 15.6L5.3 14h1.3l-.3 1.6 1.7-.3v1.3l-1.6-.3.3 1.7H5.3l.3-1.6-1.6.3v-1.3l1.6.2z"
                mask="url(#GE__mask-2_4_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#fd0d1b"
            />
            <defs>
                <filter
                    id="GE__Adobe_OpacityMaskFilter_4_"
                    filterUnits="userSpaceOnUse"
                    x={20}
                    y={14}
                    width={4}
                    height={4}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={20} y={14} width={4} height={4} id="GE__mask-2_5_">
                <g filter="url(#GE__Adobe_OpacityMaskFilter_4_)">
                    <path
                        id="GE__path-1_5_"
                        className="GE__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                d="M21.6 15.6l-.3-1.6h1.3l-.3 1.6 1.6-.3v1.3l-1.6-.3.3 1.6h-1.3l.3-1.6-1.6.4v-1.3l1.6.2z"
                mask="url(#GE__mask-2_5_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#fd0d1b"
            />
        </svg>
    );
};
export default GE;
