// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const GM: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="GM__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="GM__b" fill="#fff">
                    <use xlinkHref="#GM__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#GM__a" />
                <path fill="#DF2237" mask="url(#GM__b)" d="M0 0h28v6.667H0z" />
                <path fill="#4B9334" mask="url(#GM__b)" d="M0 13.333h28V20H0z" />
                <path fill="#FFF" mask="url(#GM__b)" d="M0 6.667h28v6.667H0z" />
                <path fill="#1526A7" mask="url(#GM__b)" d="M0 8h28v4H0z" />
            </g>
        </svg>
    );
};
export default GM;
