// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const GR: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 20">
            <path
                d="M2 0h24c1.1 0 2 .9 2 2.1V18c0 1.1-.9 2.1-2 2.1H2c-1.1 0-2-.9-2-2.1V2.1C0 .9.9 0 2 0z"
                fill="#f5f5f5"
            />
            <defs>
                <filter id="GR__a" filterUnits="userSpaceOnUse" x={0} y={0} width={28} height={18.7}>
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={18.7} id="GR__b">
                <g filter="url(#GR__a)">
                    <path
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                        fillRule="evenodd"
                        clipRule="evenodd"
                        fill="#fff"
                    />
                </g>
            </mask>
            <path
                d="M13.3 13.3H8V8h5.3v2.7H28v2.7H13.3zm0-13.3H28v2.7H13.3v2.7H8V0h5.3zM0 0h5.3v5.3H0V0zm13.3 5.3H28V8H13.3V5.3zM0 16h28v2.7H0V16zm0-8h5.3v5.3H0V8z"
                mask="url(#GR__b)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#1c6dc1"
            />
        </svg>
    );
};
export default GR;
