// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const HR: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="HR__Ebene_1"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.HR__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h24c1.1 0 2 .9 2 2v15.5c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#f5f5f5" />
            <defs>
                <filter
                    id="HR__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={6.7} id="HR__mask-2_1_">
                <g filter="url(#HR__Adobe_OpacityMaskFilter)">
                    <path
                        id="HR__path-1_1_"
                        className="HR__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="HR__Rectangle-2"
                mask="url(#HR__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ff202d"
                d="M0 0h28v6.7H0z"
            />
            <defs>
                <filter
                    id="HR__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={10.7}
                    y={4.7}
                    width={6.7}
                    height={2}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={10.7} y={4.7} width={6.7} height={2} id="HR__mask-2_2_">
                <g filter="url(#HR__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="HR__path-1_2_"
                        className="HR__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="HR__Rectangle-675"
                d="M10.7 5.3l.7-.7.6.7v1.3h-1.3V5.3zm2.6 0l.7-.6.7.7v1.3h-1.3V5.3zm2.7 0l.7-.7.7.7v1.3H16V5.3z"
                opacity={0.5}
                mask="url(#HR__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#1895db"
                enableBackground="new"
            />
            <defs>
                <filter
                    id="HR__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={12}
                    y={4.7}
                    width={4}
                    height={2}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={12} y={4.7} width={4} height={2} id="HR__mask-2_3_">
                <g filter="url(#HR__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="HR__path-1_3_"
                        className="HR__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                d="M12 5.3l.7-.7.7.7v1.3H12V5.3zm2.7 0l.7-.7.6.7v1.3h-1.3V5.3z"
                opacity={0.5}
                mask="url(#HR__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#191f94"
                enableBackground="new"
            />
            <defs>
                <filter
                    id="HR__Adobe_OpacityMaskFilter_3_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={13.3}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={13.3} width={28} height={6.7} id="HR__mask-2_4_">
                <g filter="url(#HR__Adobe_OpacityMaskFilter_3_)">
                    <path
                        id="HR__path-1_4_"
                        className="HR__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#HR__mask-2_4_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#2027ac"
                d="M0 13.3h28V20H0z"
            />
            <defs>
                <filter
                    id="HR__Adobe_OpacityMaskFilter_4_"
                    filterUnits="userSpaceOnUse"
                    x={10.7}
                    y={6.7}
                    width={6.7}
                    height={8}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={10.7} y={6.7} width={6.7} height={8} id="HR__mask-2_5_">
                <g filter="url(#HR__Adobe_OpacityMaskFilter_4_)">
                    <path
                        id="HR__path-1_5_"
                        className="HR__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <linearGradient
                id="HR__Rectangle-657_1_"
                gradientUnits="userSpaceOnUse"
                x1={-240.05}
                y1={379.515}
                x2={-240.05}
                y2={378.515}
                gradientTransform="matrix(6.6667 0 0 -8 1614.333 3042.785)"
            >
                <stop offset={0} stopColor="#ff212e" />
                <stop offset={1} stopColor="#fd0d1b" />
            </linearGradient>
            <path
                id="HR__Rectangle-657"
                d="M13.3 6.7h1.3V8h-1.3V6.7zm2.7 0h.7l.6 1.3H16V6.7zm-4.7 0h.7V8h-1.3l.6-1.3zM12 8h1.3v1.3H12V8zm2.7 0H16v1.3h-1.3V8zm-1.4 1.3h1.3v1.3h-1.3V9.3zm2.7 0h1.3v1.3H16V9.3zm-1.3 1.4H16V12h-1.3v-1.3zm-4-1.4H12v1.3h-1.3V9.3zm1.3 1.4h1.3V12H12v-1.3zM10.7 12H12v1.3h-1.3V12zm2.6 0h1.3v1.3h-1.3V12zm2.7 0h1.3v1.3H16V12zm-1.3 1.3H16v1.3h-1.3v-1.3zm-2.7 0h1.3v1.3H12v-1.3z"
                mask="url(#HR__mask-2_5_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="url(#HR__Rectangle-657_1_)"
            />
        </svg>
    );
};

HR.defaultProps = {};
export default HR;
