// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const JE: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="JE__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.JE__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <g id="JE__JE">
                <path d="M2 0h24c1.1 0 2 .9 2 2v15.9c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
                <defs>
                    <filter
                        id="JE__Adobe_OpacityMaskFilter"
                        filterUnits="userSpaceOnUse"
                        x={-6.3}
                        y={-4.8}
                        width={41.9}
                        height={30.5}
                    >
                        <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                    </filter>
                </defs>
                <mask maskUnits="userSpaceOnUse" x={-6.3} y={-4.8} width={41.9} height={30.5} id="JE__mask-2_1_">
                    <g filter="url(#JE__Adobe_OpacityMaskFilter)">
                        <path
                            id="JE__path-1_1_"
                            className="JE__st2"
                            d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                        />
                    </g>
                </mask>
                <path
                    id="JE__Rectangle-1278"
                    transform="rotate(-55 14.658 10.473)"
                    mask="url(#JE__mask-2_1_)"
                    fillRule="evenodd"
                    clipRule="evenodd"
                    fill="#e3243b"
                    d="M13.3-14.2H16v49.3h-2.7z"
                />
                <defs>
                    <filter
                        id="JE__Adobe_OpacityMaskFilter_1_"
                        filterUnits="userSpaceOnUse"
                        x={-6.3}
                        y={-4.8}
                        width={41.9}
                        height={30.5}
                    >
                        <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                    </filter>
                </defs>
                <mask maskUnits="userSpaceOnUse" x={-6.3} y={-4.8} width={41.9} height={30.5} id="JE__mask-2_2_">
                    <g filter="url(#JE__Adobe_OpacityMaskFilter_1_)">
                        <path
                            id="JE__path-1_2_"
                            className="JE__st2"
                            d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                        />
                    </g>
                </mask>
                <path
                    transform="rotate(-35 14.658 10.473)"
                    mask="url(#JE__mask-2_2_)"
                    fillRule="evenodd"
                    clipRule="evenodd"
                    fill="#e3243b"
                    d="M-10 9.1h49.3v2.7H-10z"
                />
                <defs>
                    <filter
                        id="JE__Adobe_OpacityMaskFilter_2_"
                        filterUnits="userSpaceOnUse"
                        x={12.7}
                        y={1.3}
                        width={4}
                        height={6.3}
                    >
                        <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                    </filter>
                </defs>
                <mask maskUnits="userSpaceOnUse" x={12.7} y={1.3} width={4} height={6.3} id="JE__mask-2_3_">
                    <g filter="url(#JE__Adobe_OpacityMaskFilter_2_)">
                        <path
                            id="JE__path-1_3_"
                            className="JE__st2"
                            d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                        />
                    </g>
                </mask>
                <g id="JE__Group" mask="url(#JE__mask-2_3_)">
                    <g transform="translate(12 1.333)">
                        <path
                            id="JE__Star-1"
                            d="M1.6 1.3L.7.7 2 .9 1.8 0l.9.7.8-.7-.1.9L4.7.8l-1 .6.1.1H1.6z"
                            fillRule="evenodd"
                            clipRule="evenodd"
                            fill="#faef32"
                        />
                        <path
                            d="M.7 3.8V2.7c0-.7.6-1.3 1.3-1.3h1.3c.7 0 1.3.6 1.3 1.3v1.2c0 1.8-2 2.5-2 2.5S.7 5.6.7 3.8z"
                            fillRule="evenodd"
                            clipRule="evenodd"
                            fill="#e3243b"
                            id="JE__Mask"
                        />
                        <defs>
                            <filter
                                id="JE__Adobe_OpacityMaskFilter_3_"
                                filterUnits="userSpaceOnUse"
                                x={2.3}
                                y={5.3}
                                width={1}
                                height={1}
                            >
                                <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                            </filter>
                        </defs>
                        <mask maskUnits="userSpaceOnUse" x={2.3} y={5.3} width={1} height={1} id="JE__mask-4_1_">
                            <g filter="url(#JE__Adobe_OpacityMaskFilter_3_)">
                                <path
                                    id="JE__path-3_1_"
                                    className="JE__st2"
                                    d="M.7 3.8V2.7c0-.7.6-1.3 1.3-1.3h1.3c.7 0 1.3.6 1.3 1.3v1.2c0 1.8-2 2.5-2 2.5S.7 5.6.7 3.8z"
                                />
                            </g>
                        </mask>
                        <path
                            id="JE__Rectangle-1281"
                            d="M2.8 5.3c.3 0 .5.2.5.5s-.2.5-.5.5-.5-.2-.5-.5c0-.2.3-.5.5-.5z"
                            mask="url(#JE__mask-4_1_)"
                            fillRule="evenodd"
                            clipRule="evenodd"
                            fill="#faef32"
                        />
                        <defs>
                            <filter
                                id="JE__Adobe_OpacityMaskFilter_4_"
                                filterUnits="userSpaceOnUse"
                                x={1.3}
                                y={4}
                                width={2.7}
                                height={1}
                            >
                                <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                            </filter>
                        </defs>
                        <mask maskUnits="userSpaceOnUse" x={1.3} y={4} width={2.7} height={1} id="JE__mask-4_2_">
                            <g filter="url(#JE__Adobe_OpacityMaskFilter_4_)">
                                <path
                                    id="JE__path-3_2_"
                                    className="JE__st2"
                                    d="M.7 3.8V2.7c0-.7.6-1.3 1.3-1.3h1.3c.7 0 1.3.6 1.3 1.3v1.2c0 1.8-2 2.5-2 2.5S.7 5.6.7 3.8z"
                                />
                            </g>
                        </mask>
                        <path
                            d="M1.8 4h1.7c.3 0 .5.2.5.5s-.2.5-.5.5H1.8c-.2 0-.5-.2-.5-.5s.3-.5.5-.5z"
                            mask="url(#JE__mask-4_2_)"
                            fillRule="evenodd"
                            clipRule="evenodd"
                            fill="#faef32"
                        />
                        <defs>
                            <filter
                                id="JE__Adobe_OpacityMaskFilter_5_"
                                filterUnits="userSpaceOnUse"
                                x={1.3}
                                y={2.7}
                                width={2.7}
                                height={1}
                            >
                                <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                            </filter>
                        </defs>
                        <mask maskUnits="userSpaceOnUse" x={1.3} y={2.7} width={2.7} height={1} id="JE__mask-4_3_">
                            <g filter="url(#JE__Adobe_OpacityMaskFilter_5_)">
                                <path
                                    id="JE__path-3_3_"
                                    className="JE__st2"
                                    d="M.7 3.8V2.7c0-.7.6-1.3 1.3-1.3h1.3c.7 0 1.3.6 1.3 1.3v1.2c0 1.8-2 2.5-2 2.5S.7 5.6.7 3.8z"
                                />
                            </g>
                        </mask>
                        <path
                            d="M1.8 2.7h1.7c.3 0 .5.2.5.5s-.2.5-.5.5H1.8c-.3 0-.5-.2-.5-.5s.3-.5.5-.5z"
                            mask="url(#JE__mask-4_3_)"
                            fillRule="evenodd"
                            clipRule="evenodd"
                            fill="#faef32"
                        />
                    </g>
                </g>
            </g>
        </svg>
    );
};
export default JE;
