// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const JO: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="JO__Ebene_1"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.JO__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h24c1.1 0 2 .9 2 2v15.9c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
            <defs>
                <filter
                    id="JO__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={13.3}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={13.3} width={28} height={6.7} id="JO__mask-2_1_">
                <g filter="url(#JO__Adobe_OpacityMaskFilter)">
                    <path
                        id="JO__path-1_1_"
                        className="JO__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="JO__Rectangle-2"
                mask="url(#JO__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#199e56"
                d="M0 13.3h28V20H0z"
            />
            <defs>
                <filter
                    id="JO__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={6.7} id="JO__mask-2_2_">
                <g filter="url(#JO__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="JO__path-1_2_"
                        className="JO__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#JO__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#262626"
                d="M0 0h28v6.7H0z"
            />
            <defs>
                <filter
                    id="JO__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={13.3}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={13.3} height={20} id="JO__mask-2_3_">
                <g filter="url(#JO__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="JO__path-1_3_"
                        className="JO__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="JO__Rectangle-83"
                mask="url(#JO__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#e6223a"
                d="M0 0l13.3 10L0 20z"
            />
            <defs>
                <filter
                    id="JO__Adobe_OpacityMaskFilter_3_"
                    filterUnits="userSpaceOnUse"
                    x={2.7}
                    y={8}
                    width={3.9}
                    height={3.8}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={2.7} y={8} width={3.9} height={3.8} id="JO__mask-2_4_">
                <g filter="url(#JO__Adobe_OpacityMaskFilter_3_)">
                    <path
                        id="JO__path-1_4_"
                        className="JO__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="JO__Star-27"
                mask="url(#JO__mask-2_4_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#fff"
                d="M4.7 11l-.9.8.1-1.2-1.2-.2 1-.6-.6-1 1.1.3.5-1.1.4 1.1 1.1-.3-.6 1 1 .6-1.2.2.1 1.2z"
            />
        </svg>
    );
};

JO.defaultProps = {};
export default JO;
