// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const KM: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="KM__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.KM__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h24c1.1 0 2 .9 2 2v15.5c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
            <defs>
                <filter
                    id="KM__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={5.3}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={5.3} id="KM__mask-2_1_">
                <g filter="url(#KM__Adobe_OpacityMaskFilter)">
                    <path
                        id="KM__path-1_1_"
                        className="KM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="KM__Rectangle-2"
                mask="url(#KM__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ffcb49"
                d="M0 0h28v5.3H0z"
            />
            <defs>
                <filter
                    id="KM__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={9.3}
                    width={28}
                    height={5.3}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={9.3} width={28} height={5.3} id="KM__mask-2_2_">
                <g filter="url(#KM__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="KM__path-1_2_"
                        className="KM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#KM__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#dc1d34"
                d="M0 9.3h28v5.3H0z"
            />
            <defs>
                <filter
                    id="KM__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={14.7}
                    width={28}
                    height={5.3}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={14.7} width={28} height={5.3} id="KM__mask-2_3_">
                <g filter="url(#KM__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="KM__path-1_3_"
                        className="KM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#KM__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#4985d4"
                d="M0 14.7h28V20H0z"
            />
            <defs>
                <filter
                    id="KM__Adobe_OpacityMaskFilter_3_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={13.3}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={13.3} height={20} id="KM__mask-2_4_">
                <g filter="url(#KM__Adobe_OpacityMaskFilter_3_)">
                    <path
                        id="KM__path-1_4_"
                        className="KM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#KM__mask-2_4_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#4ba343"
                d="M0 20l13.3-10L0 0z"
            />
            <defs>
                <filter
                    id="KM__Adobe_OpacityMaskFilter_4_"
                    filterUnits="userSpaceOnUse"
                    x={1.3}
                    y={6}
                    width={6.7}
                    height={8}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={1.3} y={6} width={6.7} height={8} id="KM__mask-2_5_">
                <g filter="url(#KM__Adobe_OpacityMaskFilter_4_)">
                    <path
                        id="KM__path-1_5_"
                        className="KM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="KM__Oval-12"
                d="M6.3 6.1c-1.7.4-3 2-3 3.9s1.3 3.4 3 3.9c-.3.1-.6.1-1 .1-2.2 0-4-1.8-4-4s1.8-4 4-4c.4 0 .7 0 1 .1zm1 1.9c-.3 0-.6-.3-.6-.7s.3-.6.6-.6.7.3.7.6-.3.7-.7.7zm0 2.7c-.4 0-.7-.3-.7-.7s.4-.7.7-.7.7.3.7.7-.3.7-.7.7zm0 2.6c-.4 0-.7-.3-.7-.7s.4-.6.7-.6.7.3.7.7-.3.6-.7.6z"
                mask="url(#KM__mask-2_5_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#fff"
            />
        </svg>
    );
};
export default KM;
