// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const KP: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="KP__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="KP__b" fill="#fff">
                    <use xlinkHref="#KP__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#KP__a" />
                <path fill="#1461B6" mask="url(#KP__b)" d="M0 0h28v4H0zM0 16h28v4H0z" />
                <path fill="#FFF" mask="url(#KP__b)" d="M0 4h28v12H0z" />
                <path fill="#F53846" mask="url(#KP__b)" d="M0 5.333h28v9.333H0z" />
                <path
                    d="M10 13.333a3.333 3.333 0 110-6.666 3.333 3.333 0 010 6.666zm0-1.995l1.96 1.359-.688-2.284L13.17 8.97l-2.384-.052L10 6.667l-.786 2.25-2.384.053 1.898 1.443-.687 2.284L10 11.337z"
                    fill="#FFF"
                    mask="url(#KP__b)"
                />
            </g>
        </svg>
    );
};
export default KP;
