// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const LC: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <defs>
                <filter x="-4.2%" y="-3.4%" width="108.3%" height="113.6%" filterUnits="objectBoundingBox" id="LC__c">
                    <feOffset dy={1} in="SourceAlpha" result="shadowOffsetOuter1" />
                    <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0" in="shadowOffsetOuter1" />
                </filter>
                <rect id="LC__a" x={0} y={0} width={28} height={20} rx={2} />
                <path id="LC__d" d="M14 2.667l6 14.666H8z" />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="LC__b" fill="#fff">
                    <use xlinkHref="#LC__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#LC__a" />
                <path fill="#86D7FF" mask="url(#LC__b)" d="M0 0h28v20H0z" />
                <g mask="url(#LC__b)">
                    <use fill="#000" filter="url(#LC__c)" xlinkHref="#LC__d" />
                    <use fill="#FFF" xlinkHref="#LC__d" />
                </g>
                <path fill="#262626" mask="url(#LC__b)" d="M14 5.333l4.667 12H9.333z" />
                <path fill="#FFDA57" mask="url(#LC__b)" d="M14 9.333l6 8H8z" />
            </g>
        </svg>
    );
};

LC.defaultProps = {};
export default LC;
