// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const MA: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="MA__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="MA__b" fill="#fff">
                    <use xlinkHref="#MA__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#MA__a" />
                <path fill="#E33B44" mask="url(#MA__b)" d="M0 0h28v20H0z" />
                <path
                    d="M16.293 13.156l-.846-2.686 2.263-1.675-2.816-.026L14 6.1l-.894 2.67-2.816.026 2.263 1.675-.846 2.686L14 11.52l2.293 1.635z"
                    stroke="#0A6135"
                    strokeWidth={1.333}
                    mask="url(#MA__b)"
                />
            </g>
        </svg>
    );
};
export default MA;
