// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const MD: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="MD__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="MD__b" fill="#fff">
                    <use xlinkHref="#MD__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#MD__a" />
                <path fill="#EB1C43" mask="url(#MD__b)" d="M13.333 0H28v20H13.333z" />
                <path fill="#115BCB" mask="url(#MD__b)" d="M0 0h9.333v20H0z" />
                <path fill="#FFD953" mask="url(#MD__b)" d="M9.333 0h9.333v20H9.333z" />
                <path
                    d="M12 8h1.333L14 6l.667 2H16v4l-2 1.333L12 12V8zm1.333 1.333v2h1.334v-2h-1.334z"
                    fill="#AF7F59"
                    mask="url(#MD__b)"
                />
            </g>
        </svg>
    );
};
export default MD;
