// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const MU: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <defs>
                <rect id="MU__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="MU__b" fill="#fff">
                    <use xlinkHref="#MU__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#MU__a" />
                <path fill="#1DBB63" mask="url(#MU__b)" d="M0 16h28v4H0z" />
                <path fill="#222B82" mask="url(#MU__b)" d="M0 5.333h28v5.333H0z" />
                <path fill="#FFD741" mask="url(#MU__b)" d="M0 10.667h28V16H0z" />
                <path fill="#F4374A" mask="url(#MU__b)" d="M0 0h28v5.333H0z" />
            </g>
        </svg>
    );
};

MU.defaultProps = {};
export default MU;
