// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const MW: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="MW__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="MW__b" fill="#fff">
                    <use xlinkHref="#MW__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#MW__a" />
                <path fill="#262626" mask="url(#MW__b)" d="M0 0h28v6.667H0z" />
                <circle fill="#E42038" mask="url(#MW__b)" cx={14} cy={7.333} r={4.667} />
                <path fill="#E42038" mask="url(#MW__b)" d="M0 6.667h28v6.667H0z" />
                <path fill="#47B849" mask="url(#MW__b)" d="M0 13.333h28V20H0z" />
            </g>
        </svg>
    );
};
export default MW;
