// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const MX: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="MX__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.MX__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path
                d="M2 0h24c1.1 0 2 .9 2 2.1V18c0 1.1-.9 2.1-2 2.1H2c-1.1 0-2-.9-2-2.1V2.1C0 .9.9 0 2 0z"
                fill="#fff"
            />
            <defs>
                <filter
                    id="MX__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={18.7}
                    y={0}
                    width={9.3}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={18.7} y={0} width={9.3} height={20} id="MX__mask-2_1_">
                <g filter="url(#MX__Adobe_OpacityMaskFilter)">
                    <path
                        id="MX__path-1_1_"
                        className="MX__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="MX__Mask"
                mask="url(#MX__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#e3283e"
                d="M18.7 0H28v20h-9.3z"
            />
            <defs>
                <filter
                    id="MX__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={9.3}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={9.3} height={20} id="MX__mask-2_2_">
                <g filter="url(#MX__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="MX__path-1_2_"
                        className="MX__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="MX__Rectangle-2"
                mask="url(#MX__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#128a60"
                d="M0 0h9.3v20H0z"
            />
            <defs>
                <filter
                    id="MX__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={10.7}
                    y={8.7}
                    width={6.7}
                    height={3.6}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={10.7} y={8.7} width={6.7} height={3.6} id="MX__mask-2_3_">
                <g filter="url(#MX__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="MX__path-1_3_"
                        className="MX__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="MX__Oval-5"
                d="M11.3 9.3c0 1 .5 1.8 1.3 2.3m2.8 0c.7-.5 1.2-1.3 1.2-2.2"
                mask="url(#MX__mask-2_3_)"
                fill="none"
                stroke="#8c9157"
                strokeWidth={1.333}
                strokeLinecap="round"
            />
            <defs>
                <filter
                    id="MX__Adobe_OpacityMaskFilter_3_"
                    filterUnits="userSpaceOnUse"
                    x={12.7}
                    y={6.7}
                    width={2.7}
                    height={4}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={12.7} y={6.7} width={2.7} height={4} id="MX__mask-2_4_">
                <g filter="url(#MX__Adobe_OpacityMaskFilter_3_)">
                    <path
                        id="MX__path-1_4_"
                        className="MX__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <ellipse
                cx={14}
                cy={8.7}
                rx={1.3}
                ry={2}
                mask="url(#MX__mask-2_4_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#c59262"
            />
        </svg>
    );
};
export default MX;
