// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const NI: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="NI__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.NI__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h24c1.1 0 2 .9 2 2v15.5c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
            <defs>
                <filter
                    id="NI__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={6.7} id="NI__mask-2_1_">
                <g filter="url(#NI__Adobe_OpacityMaskFilter)">
                    <path
                        id="NI__path-1_1_"
                        className="NI__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="NI__Rectangle-2"
                mask="url(#NI__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#1a78d6"
                d="M0 0h28v6.7H0z"
            />
            <defs>
                <filter
                    id="NI__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={13.3}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={13.3} width={28} height={6.7} id="NI__mask-2_2_">
                <g filter="url(#NI__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="NI__path-1_2_"
                        className="NI__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#NI__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#1a78d6"
                d="M0 13.3h28V20H0z"
            />
            <defs>
                <filter
                    id="NI__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={11.3}
                    y={7.3}
                    width={5.3}
                    height={5.3}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={11.3} y={7.3} width={5.3} height={5.3} id="NI__mask-2_3_">
                <g filter="url(#NI__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="NI__path-1_3_"
                        className="NI__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <circle
                id="NI__Oval-1"
                cx={14}
                cy={10}
                r={2.3}
                mask="url(#NI__mask-2_3_)"
                fill="none"
                stroke="#dbcd92"
                strokeWidth={0.667}
            />
            <defs>
                <filter
                    id="NI__Adobe_OpacityMaskFilter_3_"
                    filterUnits="userSpaceOnUse"
                    x={12.7}
                    y={8.7}
                    width={2.7}
                    height={2.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={12.7} y={8.7} width={2.7} height={2.7} id="NI__mask-2_4_">
                <g filter="url(#NI__Adobe_OpacityMaskFilter_3_)">
                    <path
                        id="NI__path-1_4_"
                        className="NI__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="NI__Rectangle-390"
                mask="url(#NI__mask-2_4_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#9cddee"
                d="M14 8.7l1.3 2.6h-2.6z"
            />
        </svg>
    );
};
export default NI;
