// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const NP: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="NP__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.NP__st1{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h23.9c1.1 0 2 .9 2 2v15.9c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
            <path
                className="NP__st1"
                d="M0 2C0 .9.9 0 2 0c.4 0 .9.2 1.2.4L17.6 10c.6.4.5.7-.2.7H8l9.7 8.5c.6.5.4.9-.3.9H2c-1.1 0-2-.9-2-2V2z"
                id="NP__Mask"
            />
            <defs>
                <filter
                    id="NP__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={18.7}
                    height={20.1}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={18.7} height={20.1} id="NP__mask-4_1_">
                <g filter="url(#NP__Adobe_OpacityMaskFilter)">
                    <path
                        id="NP__path-3_1_"
                        className="NP__st1"
                        d="M0 2C0 .9.9 0 2 0c.4 0 .9.2 1.2.4L17.6 10c.6.4.5.7-.2.7H8l9.7 8.5c.6.5.4.9-.3.9H2c-1.1 0-2-.9-2-2V2z"
                    />
                </g>
            </mask>
            <path
                id="NP__Mask-Copy"
                d="M.7.7v18.7H17L6.2 10h10.3L2.9.9C2.7.8 2.2.7 2 .7H.7zm16.7 19.1s0 0 0 0 0 0 0 0h0zm0-9.2s0 0 0 0 0 0 0 0h0z"
                mask="url(#NP__mask-4_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ee1b44"
                stroke="#0543a8"
                strokeWidth={1.333}
            />
            <defs>
                <filter
                    id="NP__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={2.8}
                    y={5.5}
                    width={5.2}
                    height={11.6}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={2.8} y={5.5} width={5.2} height={11.6} id="NP__mask-4_2_">
                <g filter="url(#NP__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="NP__path-3_2_"
                        className="NP__st1"
                        d="M0 2C0 .9.9 0 2 0c.4 0 .9.2 1.2.4L17.6 10c.6.4.5.7-.2.7H8l9.7 8.5c.6.5.4.9-.3.9H2c-1.1 0-2-.9-2-2V2z"
                    />
                </g>
            </mask>
            <path
                id="NP__Star-93"
                d="M6.9 7.8c.4-.1.7-.2 1.1-.4-.3 1.1-1.3 2-2.6 2s-2.3-.8-2.6-2c.3.2.7.3 1.1.4l.5-.5-.9-.7 1.1.1V5.5l.8.8.8-.8-.1 1.1 1.1-.1-.9.8.6.5zM5.3 16l-1 1.1.1-1.5-1.5.1 1.1-1-1.1-1 1.5.1-.1-1.5 1 1.1 1-1.1-.1 1.5 1.5-.1-1.1 1 1.1 1-1.5-.1.1 1.5-1-1.1z"
                mask="url(#NP__mask-4_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#fff"
            />
        </svg>
    );
};
export default NP;
