// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const NZ: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <defs>
                <rect id="NZ__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="NZ__b" fill="#fff">
                    <use xlinkHref="#NZ__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#NZ__a" />
                <path fill="#0A17A7" mask="url(#NZ__b)" d="M0 0h28v20H0z" />
                <path
                    d="M4.333 4.153L-.9-.333H.667l.193.062L5.44 3h1.131l5.762-3.601v.934c0 .296-.17.627-.417.803l-4.25 3.036V5.18l4.3 3.685c.377.323.185.802-.3.802-.257 0-.588-.107-.804-.261L6.56 6.333H5.429L-.333 9.935v-1.44l4.666-3.333V4.153z"
                    stroke="#FFF"
                    strokeWidth={0.667}
                    fill="#FF2E3B"
                    mask="url(#NZ__b)"
                />
                <path
                    d="M0 3.333V6h4.667v3.34c0 .364.306.66.673.66h1.32a.67.67 0 00.673-.66V6h4.658a.677.677 0 00.676-.673v-1.32a.674.674 0 00-.676-.674H7.333V0H4.667v3.333H0z"
                    fill="#FFF"
                    mask="url(#NZ__b)"
                />
                <path fill="#FF2E3B" mask="url(#NZ__b)" d="M0 4h5.333V0h1.334v4H12v1.333H6.667v4H5.333v-4H0z" />
                <path
                    fill="#CA1931"
                    mask="url(#NZ__b)"
                    d="M20 17.333l-.943.276.276-.942-.276-.943L20 16l.943-.276-.276.943.276.942zM20 4.667l-.943.276.276-.943-.276-.943.943.276.943-.276-.276.943.276.943zM24 8.667l-.943.276.276-.943-.276-.943.943.276.943-.276-.276.943.276.943zM16 10l-.943.276.276-.943-.276-.942.943.276.943-.276-.276.942.276.943z"
                />
            </g>
        </svg>
    );
};

NZ.defaultProps = {};
export default NZ;
