// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const OM: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="OM__Ebene_1"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.OM__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h24c1.1 0 2 .9 2 2v15.5c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
            <defs>
                <filter
                    id="OM__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={13.3}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={13.3} width={28} height={6.7} id="OM__mask-2_1_">
                <g filter="url(#OM__Adobe_OpacityMaskFilter)">
                    <path
                        id="OM__path-1_1_"
                        className="OM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="OM__Rectangle-2"
                mask="url(#OM__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#138e16"
                d="M0 13.3h28V20H0z"
            />
            <defs>
                <filter
                    id="OM__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={20} id="OM__mask-2_2_">
                <g filter="url(#OM__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="OM__path-1_2_"
                        className="OM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#OM__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#ed2b35"
                d="M0 20h9.3v-6.7H28V6.7H9.3V0H0z"
            />
            <defs>
                <filter
                    id="OM__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={2.1}
                    y={1.3}
                    width={5.2}
                    height={5.1}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={2.1} y={1.3} width={5.2} height={5.1} id="OM__mask-2_3_">
                <g filter="url(#OM__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="OM__path-1_3_"
                        className="OM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="OM__Star-32"
                mask="url(#OM__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#fff"
                d="M4.7 4.7L3.5 6.4l.6-2-2 .2L4 3.8 2.6 2.3l1.8 1.1.3-2.1.3 2.1 1.8-1.1-1.4 1.5 1.9.8-2.1-.2.6 2z"
            />
        </svg>
    );
};

OM.defaultProps = {};
export default OM;
