// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const PH: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="PH__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.PH__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path
                d="M2 0h24c1.1 0 2 .9 2 2.1V18c0 1.1-.9 2.1-2 2.1H2c-1.1 0-2-.9-2-2.1V2.1C0 .9.9 0 2 0z"
                fill="#fff"
            />
            <defs>
                <filter
                    id="PH__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={10}
                    width={28}
                    height={10}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={10} width={28} height={10} id="PH__mask-2_1_">
                <g filter="url(#PH__Adobe_OpacityMaskFilter)">
                    <path
                        id="PH__path-1_1_"
                        className="PH__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="PH__Combined-Shape"
                d="M0 20l13-10h15v10H0z"
                mask="url(#PH__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#dd1c34"
            />
            <defs>
                <filter
                    id="PH__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={10}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={10} id="PH__mask-2_2_">
                <g filter="url(#PH__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="PH__path-1_2_"
                        className="PH__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                d="M0 0h28v10H13L0 0z"
                mask="url(#PH__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#0d4bc3"
            />
            <defs>
                <filter
                    id="PH__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={1.3}
                    y={2.7}
                    width={9.3}
                    height={14.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={1.3} y={2.7} width={9.3} height={14.7} id="PH__mask-2_3_">
                <g filter="url(#PH__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="PH__path-1_3_"
                        className="PH__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="PH__Oval-206"
                d="M4.5 11.3l-1.1 1.8.4-2-.2-.2-2 .4 1.8-1.1v-.1-.1L1.6 8.7l2 .4c.1 0 .2-.1.2-.1l-.4-2 1.1 1.8h.2L5.8 7l-.3 2c.1 0 .1.1.2.2l2-.4L6 9.9v.2l1.8 1.1-2-.4c-.2.1-.2.2-.3.2l.4 2-1.1-1.8h-.1c-.1.1-.1.1-.2.1zm5.5-.6c-.4 0-.7-.3-.7-.7s.3-.7.7-.7.7.3.7.7-.3.7-.7.7zM2 4c-.4 0-.7-.3-.7-.7s.3-.6.7-.6.7.3.7.6-.3.7-.7.7zm0 13.3c-.4 0-.7-.3-.7-.7 0-.3.3-.6.7-.6s.7.3.7.7c0 .3-.3.6-.7.6z"
                mask="url(#PH__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#fdd64d"
            />
        </svg>
    );
};
export default PH;
