// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const RO: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <defs>
                <rect id="RO__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="RO__b" fill="#fff">
                    <use xlinkHref="#RO__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#RO__a" />
                <path fill="#E5253D" mask="url(#RO__b)" d="M13.333 0H28v20H13.333z" />
                <path fill="#0A3D9C" mask="url(#RO__b)" d="M0 0h9.333v20H0z" />
                <path fill="#FFD955" mask="url(#RO__b)" d="M9.333 0h9.333v20H9.333z" />
            </g>
        </svg>
    );
};

RO.defaultProps = {};
export default RO;
