// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const RS: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="RS__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.RS__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path
                d="M2 0h24c1.1 0 2 .9 2 2.1V18c0 1.1-.9 2.1-2 2.1H2c-1.1 0-2-.9-2-2.1V2.1C0 .9.9 0 2 0z"
                fill="#fff"
            />
            <defs>
                <filter
                    id="RS__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={6.7}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={6.7} width={28} height={6.7} id="RS__mask-2_1_">
                <g filter="url(#RS__Adobe_OpacityMaskFilter)">
                    <path
                        id="RS__path-1_1_"
                        className="RS__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="RS__Rectangle-2"
                mask="url(#RS__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#17508f"
                d="M0 6.7h28v6.7H0z"
            />
            <defs>
                <filter
                    id="RS__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={6.7} id="RS__mask-2_2_">
                <g filter="url(#RS__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="RS__path-1_2_"
                        className="RS__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#RS__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#e1444d"
                d="M0 0h28v6.7H0z"
            />
            <defs>
                <filter
                    id="RS__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={5.1}
                    y={6.4}
                    width={7.2}
                    height={8.5}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={5.1} y={6.4} width={7.2} height={8.5} id="RS__mask-2_3_">
                <g filter="url(#RS__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="RS__path-1_3_"
                        className="RS__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <g id="RS__Rectangle-1668" mask="url(#RS__mask-2_3_)">
                <g transform="translate(5.333 6.667)">
                    <path
                        className="RS__st2"
                        d="M.7 3.3c0-.9.5-2.7.5-2.7.1-.3.4-.6.8-.6h2.7c.3 0 .7.3.8.6 0 0 .5 1.8.5 2.7C6 4.2 5.5 6 5.5 6c-.1.4-.4.9-.6 1.2 0 0-.6.8-1.6.8s-1.5-.8-1.5-.8c-.3-.3-.5-.8-.6-1.2 0 0-.5-1.8-.5-2.7z"
                        id="RS__Mask"
                    />
                    <defs>
                        <filter
                            id="RS__Adobe_OpacityMaskFilter_3_"
                            filterUnits="userSpaceOnUse"
                            x={-0.3}
                            y={-0.3}
                            width={7.2}
                            height={8.5}
                        >
                            <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                        </filter>
                    </defs>
                    <mask maskUnits="userSpaceOnUse" x={-0.3} y={-0.3} width={7.2} height={8.5} id="RS__mask-4_1_">
                        <g filter="url(#RS__Adobe_OpacityMaskFilter_3_)">
                            <path
                                id="RS__path-3_1_"
                                className="RS__st2"
                                d="M.7 3.3c0-.9.5-2.7.5-2.7.1-.3.4-.6.8-.6h2.7c.3 0 .7.3.8.6 0 0 .5 1.8.5 2.7C6 4.2 5.5 6 5.5 6c-.1.4-.4.9-.6 1.2 0 0-.6.8-1.6.8s-1.5-.8-1.5-.8c-.3-.3-.5-.8-.6-1.2 0 0-.5-1.8-.5-2.7z"
                            />
                        </g>
                    </mask>
                    <path
                        id="RS__Line"
                        d="M6 .7L.7 7.3"
                        mask="url(#RS__mask-4_1_)"
                        fill="none"
                        stroke="#e1444d"
                        strokeWidth={1.333}
                        strokeLinecap="square"
                    />
                    <defs>
                        <filter
                            id="RS__Adobe_OpacityMaskFilter_4_"
                            filterUnits="userSpaceOnUse"
                            x={-0.3}
                            y={-0.3}
                            width={7.2}
                            height={8.5}
                        >
                            <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                        </filter>
                    </defs>
                    <mask maskUnits="userSpaceOnUse" x={-0.3} y={-0.3} width={7.2} height={8.5} id="RS__mask-4_2_">
                        <g filter="url(#RS__Adobe_OpacityMaskFilter_4_)">
                            <path
                                id="RS__path-3_2_"
                                className="RS__st2"
                                d="M.7 3.3c0-.9.5-2.7.5-2.7.1-.3.4-.6.8-.6h2.7c.3 0 .7.3.8.6 0 0 .5 1.8.5 2.7C6 4.2 5.5 6 5.5 6c-.1.4-.4.9-.6 1.2 0 0-.6.8-1.6.8s-1.5-.8-1.5-.8c-.3-.3-.5-.8-.6-1.2 0 0-.5-1.8-.5-2.7z"
                            />
                        </g>
                    </mask>
                    <path
                        d="M.7.7L6 7.3"
                        mask="url(#RS__mask-4_2_)"
                        fill="none"
                        stroke="#e1444d"
                        strokeWidth={1.333}
                        strokeLinecap="square"
                    />
                </g>
            </g>
        </svg>
    );
};
export default RS;
