// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const RW: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <defs>
                <filter
                    x="-5.4%"
                    y="-28.1%"
                    width="110.7%"
                    height="156.2%"
                    filterUnits="objectBoundingBox"
                    id="RW__c"
                >
                    <feMorphology radius={0.5} operator="dilate" in="SourceAlpha" result="shadowSpreadOuter1" />
                    <feOffset in="shadowSpreadOuter1" result="shadowOffsetOuter1" />
                    <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0" in="shadowOffsetOuter1" />
                </filter>
                <rect id="RW__a" x={0} y={0} width={28} height={20} rx={2} />
                <path id="RW__d" d="M0 14.667h28V20H0z" />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="RW__b" fill="#fff">
                    <use xlinkHref="#RW__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#RW__a" />
                <g mask="url(#RW__b)">
                    <use fill="#000" filter="url(#RW__c)" xlinkHref="#RW__d" />
                    <use fill="#2D754D" xlinkHref="#RW__d" />
                </g>
                <path fill="#25B1EB" mask="url(#RW__b)" d="M0 0h28v9.333H0z" />
                <path
                    fill="#FECB2F"
                    mask="url(#RW__b)"
                    d="M0 9.333h28v5.333H0zM21.333 6l-1.02 1.13.078-1.52-1.521.077L20 4.667l-1.13-1.02 1.52.077-.077-1.521 1.02 1.13 1.02-1.13-.077 1.52 1.521-.077-1.13 1.02 1.13 1.021-1.52-.078.077 1.521z"
                />
            </g>
        </svg>
    );
};

RW.defaultProps = {};
export default RW;
