// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const SD: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="SD__Ebene_1"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.SD__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h24c1.1 0 2 .9 2 2v15.8c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
            <defs>
                <filter
                    id="SD__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={13.3}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={13.3} width={28} height={6.7} id="SD__mask-2_1_">
                <g filter="url(#SD__Adobe_OpacityMaskFilter)">
                    <path
                        id="SD__path-1_1_"
                        className="SD__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="SD__Rectangle-2"
                mask="url(#SD__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#262626"
                d="M0 13.3h28V20H0z"
            />
            <defs>
                <filter
                    id="SD__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={6.7} id="SD__mask-2_2_">
                <g filter="url(#SD__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="SD__path-1_2_"
                        className="SD__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path mask="url(#SD__mask-2_2_)" fillRule="evenodd" clipRule="evenodd" fill="#ea1f44" d="M0 0h28v6.7H0z" />
            <defs>
                <filter
                    id="SD__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={13.3}
                    height={20}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={13.3} height={20} id="SD__mask-2_3_">
                <g filter="url(#SD__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="SD__path-1_3_"
                        className="SD__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="SD__Rectangle-83"
                mask="url(#SD__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#12933b"
                d="M0 0l13.3 10L0 20z"
            />
        </svg>
    );
};

SD.defaultProps = {};
export default SD;
