// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const SI: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="SI__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.SI__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h24c1.1 0 2 .9 2 2v15.8c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
            <defs>
                <filter
                    id="SI__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={4.7}
                    width={28}
                    height={8.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={4.7} width={28} height={8.7} id="SI__mask-2_1_">
                <g filter="url(#SI__Adobe_OpacityMaskFilter)">
                    <path
                        id="SI__path-1_1_"
                        className="SI__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="SI__Combined-Shape"
                d="M0 6.7h5.3V5.3s1-.7 2-.7 1.9.7 1.9.7v1.3H28v6.7H0V6.7zm7.3 2.6c.7 0 1.3-.6 1.3-1.3s-.5-1.3-1.3-1.3S6 7.3 6 8s.6 1.3 1.3 1.3z"
                mask="url(#SI__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#0c47b7"
            />
            <defs>
                <filter
                    id="SI__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={13.3}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={13.3} width={28} height={6.7} id="SI__mask-2_2_">
                <g filter="url(#SI__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="SI__path-1_2_"
                        className="SI__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <g id="SI__Rectangle-2" mask="url(#SI__mask-2_2_)">
                <path id="SI__path-3" fillRule="evenodd" clipRule="evenodd" d="M0 13.3h28V20H0z" />
                <path fillRule="evenodd" clipRule="evenodd" fill="#e53b35" d="M0 13.3h28V20H0z" />
            </g>
        </svg>
    );
};
export default SI;
