// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const SM: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="SM__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.SM__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h24c1.1 0 2 .9 2 2v15.8c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
            <defs>
                <filter
                    id="SM__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={9.3}
                    width={28}
                    height={10.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={9.3} width={28} height={10.7} id="SM__mask-3_1_">
                <g filter="url(#SM__Adobe_OpacityMaskFilter)">
                    <path
                        id="SM__path-2_1_"
                        className="SM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="SM__Rectangle-2"
                mask="url(#SM__mask-3_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#7cccf5"
                d="M0 9.3h28V20H0z"
            />
            <defs>
                <filter
                    id="SM__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={10.7}
                    y={8.7}
                    width={6.7}
                    height={3.6}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={10.7} y={8.7} width={6.7} height={3.6} id="SM__mask-3_2_">
                <g filter="url(#SM__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="SM__path-2_2_"
                        className="SM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="SM__Oval-5"
                d="M11.3 9.3c0 1 .5 1.8 1.3 2.3m2.8 0c.7-.5 1.2-1.3 1.2-2.2"
                mask="url(#SM__mask-3_2_)"
                fill="none"
                stroke="#445f42"
                strokeWidth={1.333}
                strokeLinecap="round"
            />
            <defs>
                <filter
                    id="SM__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={12.7}
                    y={6.7}
                    width={2.7}
                    height={4}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={12.7} y={6.7} width={2.7} height={4} id="SM__mask-3_3_">
                <g filter="url(#SM__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="SM__path-2_3_"
                        className="SM__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <ellipse
                cx={14}
                cy={8.7}
                rx={1.3}
                ry={2}
                mask="url(#SM__mask-3_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#d89f3d"
            />
        </svg>
    );
};
export default SM;
