// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const SV: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="SV__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.SV__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h24c1.1 0 2 .9 2 2v15.8c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
            <defs>
                <filter
                    id="SV__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={6.7} id="SV__mask-2_1_">
                <g filter="url(#SV__Adobe_OpacityMaskFilter)">
                    <path
                        id="SV__path-1_1_"
                        className="SV__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="SV__Rectangle-2"
                mask="url(#SV__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#1b57c4"
                d="M0 0h28v6.7H0z"
            />
            <defs>
                <filter
                    id="SV__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={13.3}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={13.3} width={28} height={6.7} id="SV__mask-2_2_">
                <g filter="url(#SV__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="SV__path-1_2_"
                        className="SV__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#SV__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#1b57c4"
                d="M0 13.3h28V20H0z"
            />
            <defs>
                <filter
                    id="SV__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={11.3}
                    y={7.9}
                    width={5.3}
                    height={4.8}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={11.3} y={7.9} width={5.3} height={4.8} id="SV__mask-2_3_">
                <g filter="url(#SV__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="SV__path-1_3_"
                        className="SV__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <linearGradient
                id="SV__Oval-12_1_"
                gradientUnits="userSpaceOnUse"
                x1={-229.438}
                y1={345.267}
                x2={-229.438}
                y2={344.267}
                gradientTransform="matrix(5.3333 0 0 -4.8002 1237.667 1665.205)"
            >
                <stop offset={0} stopColor="#3c7839" />
                <stop offset={1} stopColor="#31642e" />
            </linearGradient>
            <path
                id="SV__Oval-12"
                d="M12.4 7.9l.9 2.8h1.3l.9-2.8c.6.5 1.1 1.3 1.1 2.1 0 1.5-1.2 2.7-2.7 2.7s-2.7-1.2-2.7-2.7c.1-.9.6-1.6 1.2-2.1z"
                mask="url(#SV__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="url(#SV__Oval-12_1_)"
            />
            <defs>
                <filter
                    id="SV__Adobe_OpacityMaskFilter_3_"
                    filterUnits="userSpaceOnUse"
                    x={13.3}
                    y={7.3}
                    width={1.3}
                    height={3.3}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={13.3} y={7.3} width={1.3} height={3.3} id="SV__mask-2_4_">
                <g filter="url(#SV__Adobe_OpacityMaskFilter_3_)">
                    <path
                        id="SV__path-1_4_"
                        className="SV__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="SV__Rectangle-483"
                mask="url(#SV__mask-2_4_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#f9c92e"
                d="M14 7.3l.7 3.4h-1.4z"
            />
        </svg>
    );
};
export default SV;
