// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const SY: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            id="SY__Ebene_1"
            xmlns="http://www.w3.org/2000/svg"
            x={0}
            y={0}
            viewBox="0 0 28 20"
            xmlSpace="preserve"
        >
            <style>{'.SY__st2{fill-rule:evenodd;clip-rule:evenodd;fill:#fff}'}</style>
            <path d="M2 0h24c1.1 0 2 .9 2 2v15.8c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z" fill="#fff" />
            <defs>
                <filter
                    id="SY__Adobe_OpacityMaskFilter"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={13.3}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={13.3} width={28} height={6.7} id="SY__mask-2_1_">
                <g filter="url(#SY__Adobe_OpacityMaskFilter)">
                    <path
                        id="SY__path-1_1_"
                        className="SY__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="SY__Rectangle-2"
                mask="url(#SY__mask-2_1_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#262626"
                d="M0 13.3h28V20H0z"
            />
            <defs>
                <filter
                    id="SY__Adobe_OpacityMaskFilter_1_"
                    filterUnits="userSpaceOnUse"
                    x={0}
                    y={0}
                    width={28}
                    height={6.7}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={0} y={0} width={28} height={6.7} id="SY__mask-2_2_">
                <g filter="url(#SY__Adobe_OpacityMaskFilter_1_)">
                    <path
                        id="SY__path-1_2_"
                        className="SY__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#SY__mask-2_2_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#e32139"
                d="M0 0h28v6.7H0z"
            />
            <defs>
                <filter
                    id="SY__Adobe_OpacityMaskFilter_2_"
                    filterUnits="userSpaceOnUse"
                    x={6.8}
                    y={7.3}
                    width={5.1}
                    height={4.8}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={6.8} y={7.3} width={5.1} height={4.8} id="SY__mask-2_3_">
                <g filter="url(#SY__Adobe_OpacityMaskFilter_2_)">
                    <path
                        id="SY__path-1_3_"
                        className="SY__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                id="SY__Star-33"
                mask="url(#SY__mask-2_3_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#128a49"
                d="M9.3 11.1l-1.5 1.1.5-1.9-1.5-1.1 1.9-.1.6-1.8.7 1.8 1.9.1-1.5 1.1.5 1.9z"
            />
            <defs>
                <filter
                    id="SY__Adobe_OpacityMaskFilter_3_"
                    filterUnits="userSpaceOnUse"
                    x={16.1}
                    y={7.3}
                    width={5.1}
                    height={4.8}
                >
                    <feColorMatrix values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0" />
                </filter>
            </defs>
            <mask maskUnits="userSpaceOnUse" x={16.1} y={7.3} width={5.1} height={4.8} id="SY__mask-2_4_">
                <g filter="url(#SY__Adobe_OpacityMaskFilter_3_)">
                    <path
                        id="SY__path-1_4_"
                        className="SY__st2"
                        d="M2 0h24c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H2c-1.1 0-2-.9-2-2V2C0 .9.9 0 2 0z"
                    />
                </g>
            </mask>
            <path
                mask="url(#SY__mask-2_4_)"
                fillRule="evenodd"
                clipRule="evenodd"
                fill="#128a49"
                d="M18.7 11.1l-1.6 1.1.5-1.9-1.5-1.1 1.9-.1.7-1.8.6 1.8 1.9.1-1.5 1.1.5 1.9z"
            />
        </svg>
    );
};
export default SY;
