// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const TG: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="TG__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="TG__b" fill="#fff">
                    <use xlinkHref="#TG__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#TG__a" />
                <path fill="#FFD44D" mask="url(#TG__b)" d="M0 0h28v20H0z" />
                <path d="M12 0h16v4H12V0zm0 8h16v4H12V8zM0 16h28v4H0v-4z" fill="#159A74" mask="url(#TG__b)" />
                <path fill="#ED1F45" mask="url(#TG__b)" d="M0 0h12v12H0z" />
                <path
                    fill="#FFF"
                    mask="url(#TG__b)"
                    d="M6 7.56L3.649 9.236l.867-2.754-2.32-1.718 2.887-.026L6 2l.917 2.738 2.887.026-2.32 1.718.867 2.754z"
                />
            </g>
        </svg>
    );
};
export default TG;
