// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const UA: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="UA__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="UA__b" fill="#fff">
                    <use xlinkHref="#UA__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#UA__a" />
                <path fill="#156DD1" mask="url(#UA__b)" d="M0 0h28v10.667H0z" />
                <path fill="#FFD948" mask="url(#UA__b)" d="M0 10.667h28V20H0z" />
            </g>
        </svg>
    );
};
export default UA;
