// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const US: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="US__e">
                    <stop stopColor="#FFF" offset="0%" />
                    <stop stopColor="#F0F0F0" offset="100%" />
                </linearGradient>
                <filter x="-5.4%" y="-7.5%" width="110.7%" height="130%" filterUnits="objectBoundingBox" id="US__c">
                    <feOffset dy={1} in="SourceAlpha" result="shadowOffsetOuter1" />
                    <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0" in="shadowOffsetOuter1" />
                </filter>
                <rect id="US__a" x={0} y={0} width={28} height={20} rx={2} />
                <path
                    d="M2 2.667a.667.667 0 110-1.334.667.667 0 010 1.334zm2.667 0a.667.667 0 110-1.334.667.667 0 010 1.334zm2.666 0a.667.667 0 110-1.334.667.667 0 010 1.334zm2.667 0a.667.667 0 110-1.334.667.667 0 010 1.334zM3.333 4a.667.667 0 110-1.333.667.667 0 010 1.333zM6 4a.667.667 0 110-1.333A.667.667 0 016 4zm2.667 0a.667.667 0 110-1.333.667.667 0 010 1.333zM10 5.333A.667.667 0 1110 4a.667.667 0 010 1.333zm-2.667 0a.667.667 0 110-1.333.667.667 0 010 1.333zm-2.666 0a.667.667 0 110-1.333.667.667 0 010 1.333zM2 5.333A.667.667 0 112 4a.667.667 0 010 1.333zm1.333 1.334a.667.667 0 110-1.334.667.667 0 010 1.334zm2.667 0a.667.667 0 110-1.334.667.667 0 010 1.334zm2.667 0a.667.667 0 110-1.334.667.667 0 010 1.334zM10 8a.667.667 0 110-1.333A.667.667 0 0110 8zM7.333 8a.667.667 0 110-1.333.667.667 0 010 1.333zM4.667 8a.667.667 0 110-1.333.667.667 0 010 1.333zM2 8a.667.667 0 110-1.333A.667.667 0 012 8z"
                    id="US__d"
                />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="US__b" fill="#fff">
                    <use xlinkHref="#US__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#US__a" />
                <path
                    d="M0 0h28v1.333H0V0zm0 2.667h28V4H0V2.667zm0 2.666h28v1.334H0V5.333zM0 8h28v1.333H0V8zm0 2.667h28V12H0v-1.333zm0 2.666h28v1.334H0v-1.334zM0 16h28v1.333H0V16zm0 2.667h28V20H0v-1.333z"
                    fill="#D02F44"
                    mask="url(#US__b)"
                />
                <path fill="#46467F" mask="url(#US__b)" d="M0 0h12v9.333H0z" />
                <g mask="url(#US__b)">
                    <use fill="#000" filter="url(#US__c)" xlinkHref="#US__d" />
                    <use fill="url(#US__e)" xlinkHref="#US__d" />
                </g>
            </g>
        </svg>
    );
};
export default US;
