// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;

const VC: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 28 20">
            <defs>
                <rect id="VC__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="VC__b" fill="#fff">
                    <use xlinkHref="#VC__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#VC__a" />
                <path fill="#08C47A" mask="url(#VC__b)" d="M13.333 0H28v20H13.333z" />
                <path fill="#0C87E1" mask="url(#VC__b)" d="M0 0h9.333v20H0z" />
                <path fill="#FECB2F" mask="url(#VC__b)" d="M8 0h12v20H8z" />
                <path
                    d="M14.667 8l2-4 2 4-2 4-2-4zM9.333 8l2-4 2 4-2 4-2-4zM12 13.333l2-4 2 4-2 4-2-4z"
                    fill="#08C47A"
                    mask="url(#VC__b)"
                />
            </g>
        </svg>
    );
};

VC.defaultProps = {};
export default VC;
