// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = Omit<IconProps, 'color'>;
const WW: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 28 20"
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
        >
            <defs>
                <rect id="WW__a" x={0} y={0} width={28} height={20} rx={2} />
            </defs>
            <g fill="none" fillRule="evenodd">
                <mask id="WW__b" fill="#fff">
                    <use xlinkHref="#WW__a" />
                </mask>
                <use fill="#FFF" xlinkHref="#WW__a" />
                <path fill="#4499FC" mask="url(#WW__b)" d="M0 0h28v20H0z" />
                <path
                    d="M13.614 15.988a6.091 6.091 0 00.772 0c.915-1.085 1.502-3.072 1.6-5.321h-3.972c.098 2.249.685 4.236 1.6 5.32zm-1.831-.411c-.65-1.324-1.03-3.049-1.103-4.91H8.037a6.006 6.006 0 003.746 4.91zm1.831-11.565c-.915 1.085-1.502 3.072-1.6 5.321h3.972c-.098-2.249-.685-4.236-1.6-5.32a6.091 6.091 0 00-.772 0zm-1.831.411a6.006 6.006 0 00-3.746 4.91h2.643c.073-1.861.453-3.586 1.103-4.91zm4.434 11.154a6.006 6.006 0 003.746-4.91H17.32c-.073 1.861-.453 3.586-1.103 4.91zm0-11.154c.65 1.324 1.03 3.049 1.103 4.91h2.643a6.006 6.006 0 00-3.746-4.91zM14 17.333a7.333 7.333 0 110-14.666 7.333 7.333 0 010 14.666z"
                    fill="#FFF"
                    mask="url(#WW__b)"
                />
            </g>
        </svg>
    );
};
export default WW;
