// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const BriefcaseIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24">
            <path
                d="M14 2a2 2 0 012 2v2h6v2H4v11h16v-9h2v11H2V6h6V4a2 2 0 012-2h4zm0 2h-4v2h4V4z"
                fill="currentColor"
                fillRule="nonzero"
            />
        </svg>
    );
};

BriefcaseIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default BriefcaseIcon;
