// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = IconProps;
const PersonIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M15 11a4 4 0 014 4v7h-2v-7a2 2 0 00-2-2H9a2 2 0 00-2 2v5h8v2H5v-7a4 4 0 014-4h6zm-3.025-9c2.196 0 3.975 1.79 3.975 4s-1.78 4-3.975 4C9.78 10 8 8.21 8 6s1.78-4 3.975-4zm0 2A1.988 1.988 0 0010 6c0 1.107.887 2 1.975 2a1.988 1.988 0 001.975-2c0-1.107-.887-2-1.975-2z"
                fill="currentColor"
            />
        </svg>
    );
};
export default PersonIcon;
