// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = Omit<IconProps, 'color'>;
const StripeIcon: React.FC<Props> = ({ size = 'medium', ...props }) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M6.49 2h11.02A4.49 4.49 0 0122 6.49v11.02A4.49 4.49 0 0117.51 22H6.49A4.49 4.49 0 012 17.51V6.49A4.49 4.49 0 016.49 2zm5.756 7.066c-.637 0-1.032.215-1.032.693 0 .52.672.747 1.503 1.028 1.354.458 3.13 1.059 3.117 3.295 0 2.217-1.745 3.464-4.274 3.464a8.447 8.447 0 01-3.325-.693V13.95a7.662 7.662 0 003.367.99c.672 0 1.164-.18 1.164-.74 0-.577-.728-.84-1.607-1.156-1.336-.48-3.021-1.087-3.021-3.119 0-2.175 1.649-3.464 4.115-3.464a8.036 8.036 0 013.02.555v2.833a6.817 6.817 0 00-3.027-.783z"
                fill="#6772E5"
            />
        </svg>
    );
};
export default StripeIcon;
