// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const CogIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24" className="svg-inherit">
            <path
                d="M12 1.5L21 7v10l-9 5.5L3 17V7l9-5.5zm0 2.29L5 8.177v7.646l7 4.387 7-4.387V8.177L12 3.79zM12 8a4 4 0 110 8 4 4 0 010-8zm0 2a2 2 0 100 4 2 2 0 000-4z"
                fill="currentColor"
                fillRule="nonzero"
            />
        </svg>
    );
};

CogIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default CogIcon;
