// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { getSemanticValue } from '../../utils/cssVariables';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const EmojiKissIcon: React.FC<Props> = ({
    size = 'medium',
    color = getSemanticValue('icon-primary-default'),
    ...rest
}) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M9.879 9.5c0 .8-.69 1.5-1.477 1.5-.788 0-1.478-.7-1.478-1.5S7.614 8 8.402 8c.787 0 1.477.7 1.477 1.5zm6.894 0c0 .8-.69 1.5-1.477 1.5-.788 0-1.478-.7-1.478-1.5s.69-1.5 1.478-1.5c.787 0 1.477.7 1.477 1.5zm-1.97 4.62L12.715 12l-1.044 1.06 1.044 1.06-1.044 1.06 1.044 1.06-1.044 1.06 1.044 1.06 2.088-2.12-1.044-1.06 1.044-1.06zM17.61 13c-.536 0-1.05.216-1.428.6a2.073 2.073 0 000 2.9l3.447 3.5 3.447-3.5a2.073 2.073 0 000-2.9 2.004 2.004 0 00-1.428-.6c-.542 0-1.064.23-1.428.6l-.591.6-.591-.59A1.997 1.997 0 0017.61 13zm-1.822 5.92a7.767 7.767 0 01-3.94 1.08c-4.35 0-7.878-3.582-7.878-8s3.527-8 7.878-8c4.196 0 7.613 3.33 7.88 7.5.57-.31 1.24-.5 1.92-.5-.493-5.05-4.698-9-9.8-9C6.41 2 2 6.477 2 12s4.41 10 9.848 10c1.97 0 3.822-.6 5.368-1.62l-1.428-1.46z"
                fill="currentColor"
            />
        </svg>
    );
};
export default EmojiKissIcon;
