// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const FavoriteBannerSolidIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24">
            <path
                d="M20 2v20.508l-8-3.379-8 3.379V2h16zm-8 3.87l-1.508 3.055-3.37.49 2.439 2.378-.576 3.357L12 13.565l3.015 1.585-.576-3.357 2.44-2.378-3.371-.49L12 5.87z"
                fill="currentColor"
                fillRule="nonzero"
            />
        </svg>
    );
};

FavoriteBannerSolidIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default FavoriteBannerSolidIcon;
