// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { Colors } from '../../essentials';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;

const SheetSolidIcon: React.FC<Props> = ({ size = 'medium', ...props }: IconProps) => {
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24" className="svg-inherit">
            <path
                d="M20 2v20H4V2h16zm-8 12H8v2h4v-2zm4-4H8v2h8v-2zm-2-4H8v2h6V6z"
                fill="currentColor"
                fillRule="nonzero"
            />
        </svg>
    );
};

SheetSolidIcon.defaultProps = {
    color: Colors.AUTHENTIC_BLUE_900
};
export default SheetSolidIcon;
