// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = IconProps;
const ShoppingCartIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M8.5 17a1.5 1.5 0 110 3 1.5 1.5 0 010-3zm8 0a1.5 1.5 0 110 3 1.5 1.5 0 010-3zM3.86 4a3 3 0 012.902 2.238l.04.174 1.357 6.784c.073.392.438.747.863.797L9.14 14h7.53a1 1 0 00.912-.591l.042-.11L19.279 8H8.5l-.4-2H22l-2.467 7.895a3 3 0 01-2.677 2.1l-.187.005H9.14a3 3 0 01-2.901-2.239l-.04-.173L4.84 6.804a1 1 0 00-.863-.797L3.86 6H2V4h1.86z"
                fill="currentColor"
            />
        </svg>
    );
};
export default ShoppingCartIcon;
