// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { getSemanticValue } from '../../utils/cssVariables';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const SpeechbubblesPairIcon: React.FC<Props> = ({
    size = 'medium',
    color = getSemanticValue('foreground-primary'),
    ...rest
}) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path
                d="M23 10v13l-3-3h-6a4 4 0 01-4-4v-6h13zm-2 2h-9v4a2 2 0 002 2h7v-6zm-6-9v5h-2V5H4v6h4v2H5l-3 3V3h13z"
                fill="currentColor"
                fillRule="nonzero"
            />
        </svg>
    );
};
export default SpeechbubblesPairIcon;
