// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { getSemanticValue } from '../../utils/cssVariables';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';
type Props = IconProps;
const SpeedometerIcon: React.FC<Props> = ({
    size = 'medium',
    color = getSemanticValue('foreground-primary'),
    ...rest
}) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg {...props} width={sizePx} height={sizePx} viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path
                d="M12 4.534c5.523 0 10 4.477 10 10 0 1.046-.16 2.054-.458 3l-2.124.001a8 8 0 00-8.24-10.96l-1.164-1.844c.642-.13 1.306-.197 1.986-.197zM4.774 7.621l1.11 1.756A7.968 7.968 0 004 14.534c0 1.061.207 2.074.582 3.001H2.458A9.996 9.996 0 012 14.534a9.966 9.966 0 012.774-6.913zM7.191 4l5.39 8.536a2 2 0 11-1.774.933L5.5 5.068 7.191 4z"
                fill="currentColor"
                fillRule="nonzero"
            />
        </svg>
    );
};
export default SpeedometerIcon;
