// DO NOT EDIT. This file was generated by running `npm run generate`.;
import * as React from 'react';
import { get } from '../../utils/themeGet';
import { IconProps } from '../IconProps';

type Props = IconProps;
const StopwatchIcon: React.FC<Props> = ({ size = 'medium', color = 'inherit', ...rest }) => {
    const props = { ...rest, color };
    const sizePx = Number.isFinite(size as number)
        ? size
        : get(`iconSizes.${size}`)(props) || get('iconSizes.medium')(props);
    return (
        <svg
            {...props}
            width={sizePx}
            height={sizePx}
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
        >
            <path
                d="M15 1v2h-2v1.055A9.001 9.001 0 0112 22a9 9 0 01-1-17.945V3H9V1h6zm-3 5a7 7 0 100 14 7 7 0 000-14zm3.316 2.27l1.368 1.46-4 3.75-1.368-1.46 4-3.75z"
                fill="currentColor"
            />
        </svg>
    );
};
export default StopwatchIcon;
