// List originally from [jackocnr/intl-tel-input](https://github.com/jackocnr/intl-tel-input)
import { PhoneAreaCodeCountry } from './types/PhoneAreaCodeCountry';

const COUNTRIES: PhoneAreaCodeCountry[] = [
    { label: 'Afghanistan (‫افغانستان‬‎)', value: 'AF', dialCode: '+93' },
    { label: 'Albania (Shqipëri)', value: 'AL', dialCode: '+355' },
    { label: 'Algeria (‫الجزائر‬‎)', value: 'DZ', dialCode: '+213' },
    { label: 'American Samoa', value: 'AS', dialCode: '+1684' },
    { label: 'Andorra', value: 'AD', dialCode: '+376' },
    { label: 'Angola', value: 'AO', dialCode: '+244' },
    { label: 'Anguilla', value: 'AI', dialCode: '+1264' },
    { label: 'Antigua and Barbuda', value: 'AG', dialCode: '+1268' },
    { label: 'Argentina', value: 'AR', dialCode: '+54' },
    { label: 'Armenia (Հայաստան)', value: 'AM', dialCode: '+374' },
    { label: 'Aruba', value: 'AW', dialCode: '+297' },
    { label: 'Australia', value: 'AU', dialCode: '+61' },
    { label: 'Austria (Österreich)', value: 'AT', dialCode: '+43' },
    { label: 'Azerbaijan (Azərbaycan)', value: 'AZ', dialCode: '+994' },
    { label: 'Bahamas', value: 'BS', dialCode: '+1242' },
    { label: 'Bahrain (‫البحرين‬‎)', value: 'BH', dialCode: '+973' },
    { label: 'Bangladesh (বাংলাদেশ)', value: 'BD', dialCode: '+880' },
    { label: 'Barbados', value: 'BB', dialCode: '+1246' },
    { label: 'Belarus (Беларусь)', value: 'BY', dialCode: '+375' },
    { label: 'Belgium (België)', value: 'BE', dialCode: '+32' },
    { label: 'Belize', value: 'BZ', dialCode: '+501' },
    { label: 'Benin (Bénin)', value: 'BJ', dialCode: '+229' },
    { label: 'Bermuda', value: 'BM', dialCode: '+1441' },
    { label: 'Bhutan (འབྲུག)', value: 'BT', dialCode: '+975' },
    { label: 'Bolivia', value: 'BO', dialCode: '+591' },
    {
        label: 'Bosnia and Herzegovina (Босна и Херцеговина)',
        value: 'BA',
        dialCode: '+387'
    },
    { label: 'Botswana', value: 'BW', dialCode: '+267' },
    { label: 'Brazil (Brasil)', value: 'BR', dialCode: '+55' },
    { label: 'British Indian Ocean Territory', value: 'IO', dialCode: '+246' },
    { label: 'British Virgin Islands', value: 'VG', dialCode: '+1284' },
    { label: 'Brunei', value: 'BN', dialCode: '+673' },
    { label: 'Bulgaria (България)', value: 'BG', dialCode: '+359' },
    { label: 'Burkina Faso', value: 'BF', dialCode: '+226' },
    { label: 'Burundi (Uburundi)', value: 'BI', dialCode: '+257' },
    { label: 'Cambodia (កម្ពុជា)', value: 'KH', dialCode: '+855' },
    { label: 'Cameroon (Cameroun)', value: 'CM', dialCode: '+237' },
    { label: 'Canada', value: 'CA', dialCode: '+1' },
    { label: 'Cape Verde (Kabu Verdi)', value: 'CV', dialCode: '+238' },
    { label: 'Cayman Islands', value: 'KY', dialCode: '+1345' },
    {
        label: 'Central African Republic (République centrafricaine)',
        value: 'CF',
        dialCode: '+236'
    },
    { label: 'Chad (Tchad)', value: 'TD', dialCode: '+235' },
    { label: 'Chile', value: 'CL', dialCode: '+56' },
    { label: 'China (中国)', value: 'CN', dialCode: '+86' },
    { label: 'Christmas Island', value: 'CX', dialCode: '+61' },
    { label: 'Cocos (Keeling) Islands', value: 'CC', dialCode: '+61' },
    { label: 'Colombia', value: 'CO', dialCode: '+57' },
    { label: 'Comoros (‫جزر القمر‬‎)', value: 'KM', dialCode: '+269' },
    {
        label: 'Congo (DRC) (Jamhuri ya Kisoemokrasia ya Kongo)',
        value: 'CD',
        dialCode: '+243'
    },
    {
        label: 'Congo (Republic) (Congo-Brazzaville)',
        value: 'CG',
        dialCode: '+242'
    },
    { label: 'Cook Islands', value: 'CK', dialCode: '+682' },
    { label: 'Costa Rica', value: 'CR', dialCode: '+506' },
    { label: 'Côte d’Ivoire', value: 'CI', dialCode: '+225' },
    { label: 'Croatia (Hrvatska)', value: 'HR', dialCode: '+385' },
    { label: 'Cuba', value: 'CU', dialCode: '+53' },
    { label: 'Curaçao', value: 'CW', dialCode: '+599' },
    { label: 'Cyprus (Κύπρος)', value: 'CY', dialCode: '+357' },
    { label: 'Czech Republic (Česká republika)', value: 'CZ', dialCode: '+420' },
    { label: 'Denmark (Danmark)', value: 'DK', dialCode: '+45' },
    { label: 'Djibouti', value: 'DJ', dialCode: '+253' },
    { label: 'Dominica', value: 'DM', dialCode: '+1767' },
    {
        label: 'Dominican Republic (República Dominicana)',
        value: 'DO',
        dialCode: '+1'
    },
    { label: 'Ecuador', value: 'EC', dialCode: '+593' },
    { label: 'Egypt (‫مصر‬‎)', value: 'EG', dialCode: '+20' },
    { label: 'El Salvador', value: 'SV', dialCode: '+503' },
    {
        label: 'Equatorial Guinea (Guinea Ecuatorial)',
        value: 'GQ',
        dialCode: '+240'
    },
    { label: 'Eritrea', value: 'ER', dialCode: '+291' },
    { label: 'Estonia (Eesti)', value: 'EE', dialCode: '+372' },
    { label: 'Ethiopia', value: 'ET', dialCode: '+251' },
    { label: 'Falkland Islands (Islas Malvinas)', value: 'FK', dialCode: '+500' },
    { label: 'Faroe Islands (Føroyar)', value: 'FO', dialCode: '+298' },
    { label: 'Fiji', value: 'FJ', dialCode: '+679' },
    { label: 'Finland (Suomi)', value: 'FI', dialCode: '+358' },
    { label: 'France', value: 'FR', dialCode: '+33' },
    { label: 'French Guiana (Guyane française)', value: 'GF', dialCode: '+594' },
    {
        label: 'French Polynesia (Polynésie française)',
        value: 'PF',
        dialCode: '+689'
    },
    { label: 'Gabon', value: 'GA', dialCode: '+241' },
    { label: 'Gambia', value: 'GM', dialCode: '+220' },
    { label: 'Georgia (საქართველო)', value: 'GE', dialCode: '+995' },
    { label: 'Germany (Deutschland)', value: 'DE', dialCode: '+49' },
    { label: 'Ghana (Gaana)', value: 'GH', dialCode: '+233' },
    { label: 'Gibraltar', value: 'GI', dialCode: '+350' },
    { label: 'Greece (Ελλάδα)', value: 'GR', dialCode: '+30' },
    { label: 'Greenland (Kalaallit Nunaat)', value: 'GL', dialCode: '+299' },
    { label: 'Grenada', value: 'GD', dialCode: '+1473' },
    { label: 'Guadeloupe', value: 'GP', dialCode: '+590' },
    { label: 'Guam', value: 'GU', dialCode: '+1671' },
    { label: 'Guatemala', value: 'GT', dialCode: '+502' },
    { label: 'Guernsey', value: 'GG', dialCode: '+44' },
    { label: 'Guinea (Guinée)', value: 'GN', dialCode: '+224' },
    { label: 'Guinea-Bissau (Guiné Bissau)', value: 'GW', dialCode: '+245' },
    { label: 'Guyana', value: 'GY', dialCode: '+592' },
    { label: 'Haiti', value: 'HT', dialCode: '+509' },
    { label: 'Honduras', value: 'HN', dialCode: '+504' },
    { label: 'Hong Kong (香港)', value: 'HK', dialCode: '+852' },
    { label: 'Hungary (Magyarország)', value: 'HU', dialCode: '+36' },
    { label: 'Iceland (Ísland)', value: 'IS', dialCode: '+354' },
    { label: 'India (भारत)', value: 'IN', dialCode: '+91' },
    { label: 'Indonesia', value: 'ID', dialCode: '+62' },
    { label: 'Iran (‫ایران‬‎)', value: 'IR', dialCode: '+98' },
    { label: 'Iraq (‫العراق‬‎)', value: 'IQ', dialCode: '+964' },
    { label: 'Ireland', value: 'IE', dialCode: '+353' },
    { label: 'Isle of Man', value: 'IM', dialCode: '+44' },
    { label: 'Israel (‫ישראל‬‎)', value: 'IL', dialCode: '+972' },
    { label: 'Italy (Italia)', value: 'IT', dialCode: '+39' },
    { label: 'Jamaica', value: 'JM', dialCode: '+1' },
    { label: 'Japan (日本)', value: 'JP', dialCode: '+81' },
    { label: 'Jersey', value: 'JE', dialCode: '+44' },
    { label: 'Jordan (‫الأردن‬‎)', value: 'JO', dialCode: '+962' },
    { label: 'Kazakhstan (Казахстан)', value: 'KZ', dialCode: '+7' },
    { label: 'Kenya', value: 'KE', dialCode: '+254' },
    { label: 'Kiribati', value: 'KI', dialCode: '+686' },
    { label: 'Kosovo', value: 'XK', dialCode: '+383' },
    { label: 'Kuwait (‫الكويت‬‎)', value: 'KW', dialCode: '+965' },
    { label: 'Kyrgyzstan (Кыргызстан)', value: 'KG', dialCode: '+996' },
    { label: 'Laos (ລາວ)', value: 'LA', dialCode: '+856' },
    { label: 'Latvia (Latvija)', value: 'LV', dialCode: '+371' },
    { label: 'Lebanon (‫لبنان‬‎)', value: 'LB', dialCode: '+961' },
    { label: 'Lesotho', value: 'LS', dialCode: '+266' },
    { label: 'Liberia', value: 'LR', dialCode: '+231' },
    { label: 'Libya (‫ليبيا‬‎)', value: 'LY', dialCode: '+218' },
    { label: 'Liechtenstein', value: 'LI', dialCode: '+423' },
    { label: 'Lithuania (Lietuva)', value: 'LT', dialCode: '+370' },
    { label: 'Luxembourg', value: 'LU', dialCode: '+352' },
    { label: 'Macau (澳門)', value: 'MO', dialCode: '+853' },
    { label: 'Macedonia (FYROM) (Македонија)', value: 'MK', dialCode: '+389' },
    { label: 'Madagascar (Madagasikara)', value: 'MG', dialCode: '+261' },
    { label: 'Malawi', value: 'MW', dialCode: '+265' },
    { label: 'Malaysia', value: 'MY', dialCode: '+60' },
    { label: 'Maldives', value: 'MV', dialCode: '+960' },
    { label: 'Mali', value: 'ML', dialCode: '+223' },
    { label: 'Malta', value: 'MT', dialCode: '+356' },
    { label: 'Marshall Islands', value: 'MH', dialCode: '+692' },
    { label: 'Martinique', value: 'MQ', dialCode: '+596' },
    { label: 'Mauritania (‫موريتانيا‬‎)', value: 'MR', dialCode: '+222' },
    { label: 'Mauritius (Moris)', value: 'MU', dialCode: '+230' },
    { label: 'Mayotte', value: 'YT', dialCode: '+262' },
    { label: 'Mexico (México)', value: 'MX', dialCode: '+52' },
    { label: 'Micronesia', value: 'FM', dialCode: '+691' },
    { label: 'Moldova (Republica Moldova)', value: 'MD', dialCode: '+373' },
    { label: 'Monaco', value: 'MC', dialCode: '+377' },
    { label: 'Mongolia (Монгол)', value: 'MN', dialCode: '+976' },
    { label: 'Montenegro (Crna Gora)', value: 'ME', dialCode: '+382' },
    { label: 'Montserrat', value: 'MS', dialCode: '+1664' },
    { label: 'Morocco (‫المغرب‬‎)', value: 'MA', dialCode: '+212' },
    { label: 'Mozambique (Moçambique)', value: 'MZ', dialCode: '+258' },
    { label: 'Myanmar (Burma) (မြန်မာ)', value: 'MM', dialCode: '+95' },
    { label: 'Namibia (Namibië)', value: 'NA', dialCode: '+264' },
    { label: 'Nauru', value: 'NR', dialCode: '+674' },
    { label: 'Nepal (नेपाल)', value: 'NP', dialCode: '+977' },
    { label: 'Netherlands (Nederland)', value: 'NL', dialCode: '+31' },
    { label: 'New Caledonia (Nouvelle-Calédonie)', value: 'NC', dialCode: '+687' },
    { label: 'New Zealand', value: 'NZ', dialCode: '+64' },
    { label: 'Nicaragua', value: 'NI', dialCode: '+505' },
    { label: 'Niger (Nijar)', value: 'NE', dialCode: '+227' },
    { label: 'Nigeria', value: 'NG', dialCode: '+234' },
    { label: 'Niue', value: 'NU', dialCode: '+683' },
    { label: 'Norfolk Island', value: 'NF', dialCode: '+672' },
    {
        label: 'North Korea (조선 민주주의 인민 공화국)',
        value: 'KP',
        dialCode: '+850'
    },
    { label: 'Northern Mariana Islands', value: 'MP', dialCode: '+1670' },
    { label: 'Norway (Norge)', value: 'NO', dialCode: '+47' },
    { label: 'Oman (‫عُمان‬‎)', value: 'OM', dialCode: '+968' },
    { label: 'Pakistan (‫پاکستان‬‎)', value: 'PK', dialCode: '+92' },
    { label: 'Palau', value: 'PW', dialCode: '+680' },
    { label: 'Palestine (‫فلسطين‬‎)', value: 'PS', dialCode: '+970' },
    { label: 'Panama (Panamá)', value: 'PA', dialCode: '+507' },
    { label: 'Papua New Guinea', value: 'PG', dialCode: '+675' },
    { label: 'Paraguay', value: 'PY', dialCode: '+595' },
    { label: 'Peru (Perú)', value: 'PE', dialCode: '+51' },
    { label: 'Philippines', value: 'PH', dialCode: '+63' },
    { label: 'Poland (Polska)', value: 'PL', dialCode: '+48' },
    { label: 'Portugal', value: 'PT', dialCode: '+351' },
    { label: 'Puerto Rico', value: 'PR', dialCode: '+1' },
    { label: 'Qatar (‫قطر‬‎)', value: 'QA', dialCode: '+974' },
    { label: 'Réunion (La Réunion)', value: 'RE', dialCode: '+262' },
    { label: 'Romania (România)', value: 'RO', dialCode: '+40' },
    { label: 'Russia (Россия)', value: 'RU', dialCode: '+7' },
    { label: 'Rwanda', value: 'RW', dialCode: '+250' },
    { label: 'Saint Barthélemy', value: 'BL', dialCode: '+590' },
    { label: 'Saint Helena', value: 'SH', dialCode: '+290' },
    { label: 'Saint Kitts and Nevis', value: 'KN', dialCode: '+1869' },
    { label: 'Saint Lucia', value: 'LC', dialCode: '+1758' },
    {
        label: 'Saint Martin (Saint-Martin (partie française))',
        value: 'MF',
        dialCode: '+590'
    },
    {
        label: 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)',
        value: 'PM',
        dialCode: '+508'
    },
    { label: 'Saint Vincent and the Grenadines', value: 'VC', dialCode: '+1784' },
    { label: 'Samoa', value: 'WS', dialCode: '+685' },
    { label: 'San Marino', value: 'SM', dialCode: '+378' },
    {
        label: 'São Tomé and Príncipe (São Tomé e Príncipe)',
        value: 'ST',
        dialCode: '+239'
    },
    {
        label: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)',
        value: 'SA',
        dialCode: '+966'
    },
    { label: 'Senegal (Sénégal)', value: 'SN', dialCode: '+221' },
    { label: 'Serbia (Србија)', value: 'RS', dialCode: '+381' },
    { label: 'Seychelles', value: 'SC', dialCode: '+248' },
    { label: 'Sierra Leone', value: 'SL', dialCode: '+232' },
    { label: 'Singapore', value: 'SG', dialCode: '+65' },
    { label: 'Sint Maarten', value: 'SX', dialCode: '+1721' },
    { label: 'Slovakia (Slovensko)', value: 'SK', dialCode: '+421' },
    { label: 'Slovenia (Slovenija)', value: 'SI', dialCode: '+386' },
    { label: 'Solomon Islands', value: 'SB', dialCode: '+677' },
    { label: 'Somalia (Soomaaliya)', value: 'SO', dialCode: '+252' },
    { label: 'South Africa', value: 'ZA', dialCode: '+27' },
    { label: 'South Korea (대한민국)', value: 'KR', dialCode: '+82' },
    { label: 'South Sudan (‫جنوب السودان‬‎)', value: 'SS', dialCode: '+211' },
    { label: 'Spain (España)', value: 'ES', dialCode: '+34' },
    { label: 'Sri Lanka (ශ්‍රී ලංකාව)', value: 'LK', dialCode: '+94' },
    { label: 'Sudan (‫السودان‬‎)', value: 'SD', dialCode: '+249' },
    { label: 'Suriname', value: 'SR', dialCode: '+597' },
    { label: 'Svalbard and Jan Mayen', value: 'SJ', dialCode: '+47' },
    { label: 'Swaziland', value: 'SZ', dialCode: '+268' },
    { label: 'Sweden (Sverige)', value: 'SE', dialCode: '+46' },
    { label: 'Switzerland (Schweiz)', value: 'CH', dialCode: '+41' },
    { label: 'Syria (‫سوريا‬‎)', value: 'SY', dialCode: '+963' },
    { label: 'Taiwan (台灣)', value: 'TW', dialCode: '+886' },
    { label: 'Tajikistan', value: 'TJ', dialCode: '+992' },
    { label: 'Tanzania', value: 'TZ', dialCode: '+255' },
    { label: 'Thailand (ไทย)', value: 'TH', dialCode: '+66' },
    { label: 'Timor-Leste', value: 'TL', dialCode: '+670' },
    { label: 'Togo', value: 'TG', dialCode: '+228' },
    { label: 'Tokelau', value: 'TK', dialCode: '+690' },
    { label: 'Tonga', value: 'TO', dialCode: '+676' },
    { label: 'Trinisoad and Tobago', value: 'TT', dialCode: '+1868' },
    { label: 'Tunisia (‫تونس‬‎)', value: 'TN', dialCode: '+216' },
    { label: 'Turkey (Türkiye)', value: 'TR', dialCode: '+90' },
    { label: 'Turkmenistan', value: 'TM', dialCode: '+993' },
    { label: 'Turks and Caicos Islands', value: 'TC', dialCode: '+1649' },
    { label: 'Tuvalu', value: 'TV', dialCode: '+688' },
    { label: 'U.S. Virgin Islands', value: 'VI', dialCode: '+1340' },
    { label: 'Uganda', value: 'UG', dialCode: '+256' },
    { label: 'Ukraine (Україна)', value: 'UA', dialCode: '+380' },
    {
        label: 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)',
        value: 'AE',
        dialCode: '+971'
    },
    { label: 'United Kingdom', value: 'GB', dialCode: '+44' },
    { label: 'United States', value: 'US', dialCode: '+1' },
    { label: 'Uruguay', value: 'UY', dialCode: '+598' },
    { label: 'Uzbekistan (Oʻzbekiston)', value: 'UZ', dialCode: '+998' },
    { label: 'Vanuatu', value: 'VU', dialCode: '+678' },
    { label: 'Vatican City (Città del Vaticano)', value: 'VA', dialCode: '+39' },
    { label: 'Venezuela', value: 'VE', dialCode: '+58' },
    { label: 'Vietnam (Việt Nam)', value: 'VN', dialCode: '+84' },
    {
        label: 'Wallis and Futuna (Wallis-et-Futuna)',
        value: 'WF',
        dialCode: '+681'
    },
    { label: 'Yemen (‫اليمن‬‎)', value: 'YE', dialCode: '+967' },
    { label: 'Zambia', value: 'ZM', dialCode: '+260' },
    { label: 'Zimbabwe', value: 'ZW', dialCode: '+263' },
    { label: 'Åland Islands', value: 'AX', dialCode: '+358' }
];

export { COUNTRIES };
