name: Documentation

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Install dependencies
              uses: bahmutov/npm-install@v1
            - name: Build docs
              run: npm run build:documentation
            - uses: actions/upload-artifact@v2
              with:
                  name: docz-dist
                  path: .docz/dist

    deploy:
        if: github.ref == 'refs/heads/main'
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: docz-dist
                  path: public
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: public
                  cname: wave.free-now.com
