name: Documentation

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              uses: bahmutov/npm-install@v1
              with:
                  install-command: npm i --legacy-peer-deps
            - name: Build docs
              run: npm run build:documentation
            - uses: actions/upload-artifact@v3
              with:
                  name: storybook-dist
                  path: storybook-static

    deploy:
        if: github.ref == 'refs/heads/main'
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: storybook-dist
                  path: public
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: public
                  cname: wave.free-now.com
